### ISSUE TITLE
Question: How to access run data after an experiment has finished

### ISSUE THREAD

**Issue by cemlyn007** [neptune-ai/neptune-client#1086]
I understand `neptune.init_run` can be used with the `with_id` keyword argument to **resume** an existing run and can be used to fetch data, but is there a way to fetch run data without resuming it?

**Comment by SiddhantSadangi** [comment]
Hello @cemlyn007!
You can use `mode="read_only"` to **resume** the run in read-only mode if you want to prevent accidentally logging something to the run or updating any metadata already logged to the run.

Please let me know if this is what you were looking for :)

**Comment by cemlyn007** [comment]
Alright I'll give it a go on Monday, have a good weekend guys 😁

**Comment by cemlyn007** [comment]
Good morning, yes you're right, I forgot to specify the mode as "read-only"  when viewing my finished runs. Thank you very much and have a nice week! 👋

**Comment by SiddhantSadangi** [comment]
Glad to be of help! :)
Have a great week, and please feel free to contact us in case of any queries/issues 🖖
