### ISSUE TITLE
cannot use '.' in tags

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/neptune-client#110]
I am training to add feature version to tag as '1.0' and it results in error:

```
neptune.api_exceptions.ExperimentValidationError: Tags: [1.0] are invalid. Valid tags may contain only lowercase letters, digits, underscores and dashes.
```

**Comment by ariG23498** [comment]
Hey @jakubczakon 
I think we indeed can tag the runs with `.`
![image](https://user-images.githubusercontent.com/36856589/109014479-2e7faf00-76da-11eb-92fb-a35ded714548.png)

Could you share the code that you used so that I could reproduce it?

**Comment by Herudaio** [comment]
The tags accept all UTF-8 (almost all - all that can be coded in 3 bytes ;) ) symbols. If you want you can use emojis in your tags eg. `Exploration 🧪`
