### ISSUE TITLE
download image channel

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/neptune-client#112]
It would be useful to download images from the image channel.
For example:

```python
exp =project.get_experiment(id='PROJ-1')
exp.download_image_channel('local/dest/to/image/dir')
```

And the images would land in my 'local/dest/to/image/dir` folder.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon like this idea. Thanks a lot. Will get back to you with some specifics.

Best,
KK

**Comment by JohnCHarrington** [comment]
Did anything happen on this? I need to be able to do this

**Comment by Herudaio** [comment]
@JohnCHarrington sorry for the late response!
As of now, it's not possible to download the image series, however, we are working on it and you should be expecting it in a few weeks :)
In the meantime, there is a potential workaround - you can upload images through `log_artifact` which are later possible to download programmatically. In case you need them both visible in UI and downloadable they should be logged to both places.

**Comment by Herudaio** [comment]
@JohnCHarrington the feature I mentioned is [now available as part of neptune.new](https://docs.neptune.ai/essentials/api-reference/run/field-types#download-2) :)
You can read all about the new version of the Neptune in [the release blogpost](https://neptune.ai/blog/neptune-new).
