### ISSUE TITLE
BUG: Unable to install neptune-client in kaggle kernel

### ISSUE THREAD

**Issue by gfx73** [neptune-ai/neptune-client#1268]
neptune-client problem
I tried to install neptune-clinet couple of monthes ago and is was just fine with "!pip install neptune-client".

The error I have: ```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.4.2 requires botocore<1.27.60,>=1.27.59, but you have botocore 1.29.79 which is incompatible.```

What I've done:
1) I'm doing the installation right after factory reset in "run" tab.

2) I tried all versions of neptune-client from 0.16.11 to 1.0.0 (which is just neptune e.g. "pip install neptune")

3) As I understand neptun-client requires aiobotocore-2.4.2, aiobotocore 2.4.2 requires botocore-1.27.59. So I tried to search for some boto3 version which is compatilble. The newest compatible version I found is boto3==1.24.59. Kaggle kernel has preinstalled versions of botocore and boto3. So I tried to install neptune-client in the following way:
```
!pip uninstall botocore boto3 -y
!pip install aiobotocore botocore boto3==1.24.59 neptune-client
```

The installation itself was ok, without any erros. However at this point I got an error when trying to initialize NeptuneLogger: ```ModuleNotFoundError: FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/boto3-1.26.72.dist-info/METADATA'. HINT: Try running pip install -U 'neptune-client'```. So it seems like neptune-client needs boto3-1.26.72, which is incompatible with aiobotocore-2.4.2). Maybe I'm wrong in something. Just tried to figure out what is the source of problem.

4) It looks like this problem arrived with some kaggle environment update. I have "pin original environment" option in notebooks settings. In one notebook I have version dated by 2023-02-01. In this notebook I can just install neptune-client and everything is fine. However when I switch to "Always use the latest environment" I have the described problem. My new notebook's environment is dated by 2023-02-17. This notebook also have the described problem, and I can't switch to older environment version.

To reproduce just try ```!pip install neptune-client``` in a kaggle notebook with new environment version.

I am sorry if the issue is related not to neptune-client, but to kaggle. Anyway, I would really appreciate any help)

**Comment by Blaizzy** [comment]
Hey @gfx73 

Prince here,

Thanks for reaching out!

Could you try again?

I tried to reproduce your issue but it worked without any issues.

**Comment by gfx73** [comment]
Hi @Blaizzy 

Thanks for reply.

I created a new notebook and tried to install. The installation was successful indeed. However, once I switched environment option I am not able to install neither with “pin original environment” nor with  “Always use the latest environment”. I am doing factory reset before trying.

**Comment by Blaizzy** [comment]
> I created a new notebook and tried to install. The installation was successful indeed. However, once I switched environment option I am not able to install neither with “pin original environment” nor with “Always use the latest environment”. I am doing factory reset before trying

Are you able to install other packages besides Neptune?

**Comment by gfx73** [comment]
Yes. I installed faiss for example

**Comment by Blaizzy** [comment]
> However, once I switched environment option I am not able to install neither with “pin original environment” nor with “Always use the latest environment”. I am doing factory reset before trying

Could you elaborate on this? What do mean by changing environments? How can I reproduce this state?

**Comment by gfx73** [comment]
![img](https://user-images.githubusercontent.com/65644911/222102774-54e9e456-3220-411b-9b48-1547e091c6b7.png)
Environment option on the right side. 

I'm sorry again if the issue is on kaggle's side.

**Comment by Blaizzy** [comment]
Unfortunately, I am unable to reproduce your issue. 
I changed my environment and installed neptune again, and it works fine.
![Screenshot 2023-03-01 at 10 55 53 AM](https://user-images.githubusercontent.com/23445657/222106083-5540f689-83de-4865-b545-f5bcdbec8c86.png)

**Comment by Blaizzy** [comment]
After a deeper look, I see the error now.

But it doesn't affect your use of neptune.

I will ask the devs to investigate this issue for you and see if there is anything we can do here. Because, by the looks of Kaggle has the latest botocore installed, which results in the requirement being satisfied when installing neptune.

**Comment by gfx73** [comment]
![img](https://user-images.githubusercontent.com/65644911/222108202-b60cd69f-06bf-4887-9e29-a8b0815b6b26.png)

I can't initialize NeptuneLogger.

**Comment by Blaizzy** [comment]
What version of neptune are you running?

**Comment by gfx73** [comment]
The default which I got from pip. ```neptune.__version__``` returns 1.0.2

**Comment by Blaizzy** [comment]
We are currently working on updating the Lightning integration to support v1.0.0 changes and potentially will be available on the next release of Lightning.

You can follow it here: https://github.com/Lightning-AI/lightning/pull/16761


Meanwhile, the devs work on the update and a fix for the issue you reported, you can _temporarily_ downgrade to neptune-client to v0.16.17

`pip install neptune-client==0.16.17`

This will allow you to continue working :)

**Comment by gfx73** [comment]
Of course. Just a second, I'm trying

**Comment by gfx73** [comment]
Well, I have the same issue
![img](https://user-images.githubusercontent.com/65644911/222113624-b4ef5791-d563-4b41-888d-ae9240fc5828.png)

**Comment by Blaizzy** [comment]
Can you downgrade botocore?

**Comment by gfx73** [comment]
So should I install this way: ```pip install botocore==1.27.59 neptune-client==0.16.17```?

**Comment by gfx73** [comment]
Ok, I tried. Error remains. I have an interesting thing to add...
![img](https://user-images.githubusercontent.com/65644911/222117153-9ab1e434-fdf5-4c70-bcfa-67bd3ce91392.png)

**Comment by Blaizzy** [comment]
Try to restart the environment after you made the installation.

**Comment by gfx73** [comment]
I had this error with botocore3==1.27.59:
"ModuleNotFoundError: FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/boto3-1.26.77.dist-info/METADATA'. HINT: Try running `pip install -U 'neptune-client'"

So I tried to install boto3==1.26.77. But it's not compatible with botocore==1.27.59.

 I actually tried to resolve dependencies before creating the issue.

**Comment by Blaizzy** [comment]
There is a potential workaround.
Could you try the following:
1. Uninstall aibotocore, botocore, and s3fs.
2. Afterward, try to install neptune and s3fs.

**Comment by gfx73** [comment]
It didn't work

**Comment by Blaizzy** [comment]
What output are you getting?

**Comment by gfx73** [comment]
![img](https://user-images.githubusercontent.com/65644911/222136266-8c63acf7-23e8-4cd8-9660-51a6cc4f8c81.png)

**Comment by Blaizzy** [comment]
Thanks!

I will send it to the devs so they can look into it for you

**Comment by gfx73** [comment]
Thanks for help!

**Comment by Blaizzy** [comment]
Could you try one more sequence?

Install neptune
Uninstall aiobotocore, botocore, and s3fs
Reinstall s3fs

**Comment by gfx73** [comment]
ok

**Comment by gfx73** [comment]
Still having this problem when installing both neptune-client and s3fs:
"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
boto3 1.26.77 requires botocore<1.30.0,>=1.29.77, but you have botocore 1.27.59 which is incompatible."

And this one when initializing logger:
"ModuleNotFoundError: ContextualVersionConflict: (botocore 1.27.59 (/opt/conda/lib/python3.7/site-packages), Requirement.parse('botocore<1.30.0,>=1.29.77'), {'boto3'}). HINT: Try running `pip install -U 'neptune-client'`"

**Comment by Blaizzy** [comment]
Did you execute step 2?

**Comment by gfx73** [comment]
Yep

**Comment by Blaizzy** [comment]
Hi, I just heard from the devs that the process should be
`!pip install boto3==1.24.40`
Then:
`!pip install neptune-client`

Let me know if this helps

**Comment by Blaizzy** [comment]
Hey there,

Just checking to see if you still need help with this :)

**Comment by gfx73** [comment]
Hi.

I think the only thing I can do is to wait for update. So I currently switched to another logger. However, I like Neptune more and would be glad to continue using it)

**Comment by Blaizzy** [comment]
Hey @gfx73 

I talked to the developers, and it turns out that the issue lies with the Kaggle kernels rather than the Neptune client. 

You'll have to wait for them to resolve the problem, or you can try to file an issue on their [repository](https://github.com/Kaggle/docker-python). In the meantime, the best option we have is this one: https://github.com/neptune-ai/neptune-client/issues/1268#issuecomment-1451620163

**Comment by gfx73** [comment]
Thank you. Should I close the issue?

**Comment by gfx73** [comment]
This works https://github.com/neptune-ai/neptune-client/issues/1268#issuecomment-1451620163

**Comment by gfx73** [comment]
Thank you for help.

Have a good day)
