### ISSUE TITLE
Adding additional logs with Transformers 

### ISSUE THREAD

**Issue by MichaelRes** [neptune-ai/neptune-client#1279]
### Describe the bug

I tried to use the neptune integration for transformers. It works well BUT when I try to retrieve the run to log more stuff, it raises an error. 

### Reproduction

training.py:
from datasets import load_dataset
from transformers import AutoTokenizer
from transformers import DefaultDataCollator
from transformers.integrations import NeptuneCallback

import neptune.new as neptune
import os

os.environ[
    "NEPTUNE_API_TOKEN"] = "my_token"
os.environ["NEPTUNE_PROJECT"] = "my_project"

squad = load_dataset("squad", split="train[:10]")

squad = squad.train_test_split(test_size=0.2)

print(squad["train"][0])

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def preprocess_function(examples):
    questions = [q.strip() for q in examples["question"]]

    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=384,
        truncation="only_second",
        return_offsets_mapping=True,
        padding="max_length",
    )

    offset_mapping = inputs.pop("offset_mapping")
    answers = examples["answers"]
    start_positions = []
    end_positions = []

    for i, offset in enumerate(offset_mapping):
        answer = answers[i]
        start_char = answer["answer_start"][0]
        end_char = answer["answer_start"][0] + len(answer["text"][0])
        sequence_ids = inputs.sequence_ids(i)

        # Find the start and end of the context
        idx = 0
        while sequence_ids[idx] != 1:
            idx += 1
        context_start = idx
        while sequence_ids[idx] == 1:
            idx += 1
        context_end = idx - 1

        # If the answer is not fully inside the context, label it (0, 0)
        if offset[context_start][0] > end_char or offset[context_end][1] < start_char:
            start_positions.append(0)
            end_positions.append(0)
        else:
            # Otherwise it's the start and end token positions
            idx = context_start
            while idx <= context_end and offset[idx][0] <= start_char:
                idx += 1
            start_positions.append(idx - 1)

            idx = context_end
            while idx >= context_start and offset[idx][1] >= end_char:
                idx -= 1
            end_positions.append(idx + 1)

    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions
    return inputs

tokenized_squad = squad.map(preprocess_function, batched=True, remove_columns=squad["train"].column_names)
data_collator = DefaultDataCollator()

from transformers import AutoModelForQuestionAnswering, TrainingArguments, Trainer

model = AutoModelForQuestionAnswering.from_pretrained("distilbert-base-uncased")

# First Method

training_args = TrainingArguments(
    output_dir="my_awesome_qa_model",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    push_to_hub=False,
    no_cuda=True,
    report_to="neptune"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_squad["train"],
    eval_dataset=tokenized_squad["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

run = NeptuneCallback.get_run(trainer)
run['test'] = 'test'

trainer.train()

### Expected behavior
These two lines should be runnable "
run = NeptuneCallback.get_run(trainer)
run['test'] = 'test'
"
### Traceback
Traceback (most recent call last):
  File "/workdir/training.py", line 114, in <module>
    run = NeptuneCallback.get_run(trainer)
  File "/opt/conda/lib/python3.10/site-packages/transformers/integrations.py", line 1303, in get_run
    return callback.run
  File "/opt/conda/lib/python3.10/site-packages/transformers/integrations.py", line 1206, in run
    self._ensure_at_least_run_without_monitoring()
  File "/opt/conda/lib/python3.10/site-packages/transformers/integrations.py", line 1194, in _ensure_at_least_run_without_monitoring
    self._initialize_run(
  File "/opt/conda/lib/python3.10/site-packages/transformers/integrations.py", line 1164, in _initialize_run
    self._run = init_run(**self._init_run_kwargs, **additional_neptune_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/neptune/internal/init/run.py", line 223, in init_run
    _check_for_extra_kwargs(init_run.__name__, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/neptune/internal/init/run.py", line 94, in _check_for_extra_kwargs
    raise TypeError(f"{caller_name}() got an unexpected keyword argument '{first_key}'")
TypeError: init_run() got an unexpected keyword argument 'run'

### Environment
**The output of `pip list`:**
```
datasets==2.9.0
transformers==4.26.1
evaluate==0.4.0
neptune==1.0.2
```
**The operating system you're using:**
macOS 13.0
**The output of `python --version`:**
Python 3.10.8
### Additional context

I tried to achieve the same goal with the NeptuneCallback method instead (setting report_to to "none" and use a NeptuneCallback instance instead) but it also fails.

**Comment by SiddhantSadangi** [comment]
Hello @MichaelRes,

Our transformers integration does not support neptune-client>=1.0.0.
Can you please try uninstalling `neptune` and installing `neptune-client<1.0.0`?

```
pip uninstall neptune
pip install "neptune-client<1.0.0"
```

Please let us know if this does not resolve your issue.

**Comment by Blaizzy** [comment]
Hi @MichaelRes 

Prince here, 

I just wanted to check in and see if you still need any assistance with this issue. If so, please don't hesitate to let us know, and we'll be more than happy to help you!

**Comment by SiddhantSadangi** [comment]
Hello @MichaelRes - we are closing this issue for now, but please don't hesitate to reopen this or reach out to us if you need any further help.
