### ISSUE TITLE
BUG: NeptuneCallback for lightgbm doesn't work properly

### ISSUE THREAD

**Issue by kananmaham** [neptune-ai/neptune-client#1298]
### Describe the bug
I am passing NeptuneCallback from lightgbm integration, and after training I am using create_booster_summary for log model summary to the neptune. But it cannot find path for writing or reading the feature importance images. However, it produces these images and show in jupyter notebook output. 
### Reproduction
```python
import neptune
from neptune.integrations.lightgbm import NeptuneCallback, create_booster_summary

run= neptune.init_run(project=project_name, tags=tags, name=run_name)
neptune_callback = NeptuneCallback(run=self.run_neptune)
model = lgbm.train(
                    params=params,
                    train_set=lgbm_train,
                    categorical_feature=categorical_features,
                    verbose_eval=-1,
                    callbacks=[neptune_callback],
                )
run["lgbm_summary"] = create_booster_summary(
                    booster=model,
                    log_trees=True,
                    list_trees=[0, 1, 2, 3, 4],
                    y_pred=preds,
                    y_true=actual,
                )
```
### Expected behavior
Automatic logging to UI with NeptuneCallback
### Traceback
def save(self, path):
--> 112     with open(path, "wb") as f:
    113         f.write(self._content)

FileNotFoundError: [Errno 2] No such file or directory: '.neptune\\async\\run__98b1afa4-1833-4f4a-bf02-0e08ecce9b93\\exec-1678889235.55935-2023-03-15_18.07.15.559350\\upload_path\\lgbm_summary_visualizations_feature_importances_split-1678889263.70142-2023-03-15_18.07.43.701420.png'
### Environment
```
neptune              1.0.2
neptune-lightgbm     1.0.0
Windows 10
Python 3.9.11
```

**Comment by kananmaham** [comment]
I tried to use the 'upload' method separately, for logging images. It is supposed to log figures, but looking for files under .neptune/async/run_../exec_.../upload_path. Below is example code, and I checked data type of ax.figure, it is `matplotlib.figure.Figure`. But I couldn't log it, it gave the same error as above.

```python
gain = model.feature_importance("gain")
df_feat_imp = pd.DataFrame(
            {
                "feature": model.feature_name(),
                "split": model.feature_importance("split"),
                "gain": 100 * gain / gain.sum(),
            }
        ).sort_values("gain", ascending=False)

plt.figure(figsize=(10, 8))
sns.set(font_scale=1)
ax = sns.barplot(x="gain", y="feature", data=df_feat_imp[0:25])
plt.title("feature")
plt.tight_layout()

for i in ax.containers:
    ax.bar_label(
                i,
            )

run['lgbm_summary/feature_importances'].upload(ax.figure)
```

**Comment by Blaizzy** [comment]
Hey @kananmaham 

Prince here, 

This behavior is strange. Our integration takes care of logging feature importance figures for you.

Let me check with the devs and come back to you.

**Comment by Blaizzy** [comment]
Hey @kananmaham,

Just a heads up - we've discovered a bug that might be affecting your experience. Our team is already working on fixing it, but we don't have an exact ETA at the moment. 

No worries though; I'll let you know once the fix is released.

**Comment by kananmaham** [comment]
Thanks for your consideration. I wanted to let you know that same happens when I try to upload LightGBM model as pickle file. 
```python
from neptune.types import File

booster = lgb.train(...)
run["model/pickled_model"].upload(File.as_pickle(booster))

```

**Comment by Blaizzy** [comment]
Hi @kananmaham 

Most welcome!

Could you share the entire reproducible code example and traceback error? 

**Note**: Don't forget to redact your API token and project name.

**Comment by Blaizzy** [comment]
@AleksanderWWW ^^

I know you were working on LightGBM integration.

Here is an issue related to it.
