### ISSUE TITLE
Feature Request: add billable hours/logging hours column

### ISSUE THREAD

**Issue by orena1** [neptune-ai/neptune-client#1310]
Not sure if it already exists (and also where to ask questions), but I could not find a way to add billable hours column here:
![image](https://user-images.githubusercontent.com/8983713/227541449-c17806a3-2180-4164-be8b-dcf1b7dcbbd1.png)

So it would be great if once can see how many billable hours each run consumed.
Thanks

**Comment by SiddhantSadangi** [comment]
Hey @orena1 ,

You can add `monitoring_time` to the table
![image](https://user-images.githubusercontent.com/41324509/227547558-d32f5978-87c7-401b-a45f-ce4369f28ddc.png)

We will make the naming more consistent (logging hours/billable hours/monitoring hours) across all our channels.

**Comment by SiddhantSadangi** [comment]
I am closing this for now, but please do feel free to reach out in case of any issues or feature requests :)

You can also reach us through chat (the chat icon at the bottom right of the Neptune app
![image](https://user-images.githubusercontent.com/41324509/227559179-43c36371-1c39-4dcf-88ed-ad6bbb5afdf5.png)
