### ISSUE TITLE
NeptuneCallback - AttributeError: module 'neptune' has no attribute 'handler'

### ISSUE THREAD

**Issue by tomwebber96** [neptune-ai/neptune-client#1320]
When trying to import NeptuneCallback I now get the following error:
AttributeError: module 'neptune' has no attribute 'handler'

Previosuly all has been working correctly using:
from neptune.integrations.tensorflow_keras import NeptuneCallback

Any help would be greatly appreciated.

**Comment by SiddhantSadangi** [comment]
Hello @tomwebber96 ,

Can you please share the below details to let us help you better?
* the full traceback
* output of `pip list`
* output of `python --version`

**Comment by SiddhantSadangi** [comment]
Hey @tomwebber96 , just checking if you still need help with this :)

**Comment by SiddhantSadangi** [comment]
Hello @tomwebber96 , I hope you are doing well!

I am closing this issue for now, but please do not hesitate to reopen this if your issue is not solved, or you need help with anything else.

Have a great day! :)
