### ISSUE TITLE
BUG: neptune-client=0.15.2 is not compatible with Python3.6 anymore

### ISSUE THREAD

**Issue by nilsmechtel** [neptune-ai/neptune-client#1329]
### Describe the bug
`neptune-client==0.15.2` is not compatible with Python3.6 anymore.
### Reproduction
Inside the `tensorflow/tensorflow:1.15.4-gpu-py3` container (Python3.6.9) install `neptune-client==0.15.2`, then `import neptune`
### Expected behavior
`import neptune` without any problems
### Traceback
>>> import neptune
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/neptune/__init__.py", line 27, in <module>
    from neptune.internal.api_clients import backend_factory
  File "/usr/local/lib/python3.6/dist-packages/neptune/internal/api_clients/__init__.py", line 17, in <module>
    from neptune.internal.api_clients.hosted_api_clients.hosted_backend_api_client import (
  File "/usr/local/lib/python3.6/dist-packages/neptune/internal/api_clients/hosted_api_clients/hosted_backend_api_client.py", line 26, in <module>
    from bravado.exception import HTTPNotFound
  File "/usr/local/lib/python3.6/dist-packages/bravado/exception.py", line 3, in <module>
    from bravado_core.response import IncomingResponse
  File "/usr/local/lib/python3.6/dist-packages/bravado_core/response.py", line 10, in <module>
    from bravado_core.unmarshal import unmarshal_schema_object
  File "/usr/local/lib/python3.6/dist-packages/bravado_core/unmarshal.py", line 17, in <module>
    from bravado_core.model import MODEL_MARKER
  File "/usr/local/lib/python3.6/dist-packages/bravado_core/model.py", line 13, in <module>
    from swagger_spec_validator.ref_validators import attach_scope
  File "/usr/local/lib/python3.6/dist-packages/swagger_spec_validator/__init__.py", line 1, in <module>
    from swagger_spec_validator.common import SwaggerValidationError
  File "/usr/local/lib/python3.6/dist-packages/swagger_spec_validator/common.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
### Environment
**The output of `pip list`:**
```
Package                Version
---------------------- ---------------
absl-py                0.10.0
asn1crypto             0.24.0
astor                  0.8.1
attrs                  22.2.0
boto3                  1.23.10
botocore               1.26.10
bravado                11.0.3
bravado-core           5.17.1
certifi                2022.12.7
charset-normalizer     2.0.12
click                  8.0.4
cryptography           2.1.4
dataclasses            0.8
future                 0.18.3
gast                   0.2.2
gitdb                  4.0.9
GitPython              3.1.18
google-pasta           0.2.0
grpcio                 1.32.0
h5py                   2.10.0
idna                   2.6
importlib-metadata     2.0.0
jmespath               0.10.0
joblib                 1.1.1
jsonpointer            2.3
jsonref                1.0.1
jsonschema             3.2.0
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
keyring                10.6.0
keyrings.alt           3.0
Markdown               3.2.2
monotonic              1.6
msgpack                1.0.5
neptune-client         0.15.2
numpy                  1.18.5
oauthlib               3.2.2
opt-einsum             3.3.0
packaging              21.3
pandas                 1.1.5
Pillow                 8.4.0
pip                    21.3.1
protobuf               3.13.0
psutil                 5.9.4
pycrypto               2.6.1
PyGObject              3.26.1
PyJWT                  2.4.0
pyparsing              3.0.9
pyrsistent             0.18.0
python-apt             1.6.5+ubuntu0.3
python-dateutil        2.8.2
pytz                   2023.3
pyxdg                  0.25
PyYAML                 6.0
requests               2.27.1
requests-oauthlib      1.3.1
rfc3987                1.3.8
s3transfer             0.5.2
scikit-learn           0.23.2
scipy                  1.5.4
SecretStorage          2.3.1
setuptools             50.3.0
simplejson             3.19.1
six                    1.16.0
smmap                  5.0.0
strict-rfc3339         0.7
swagger-spec-validator 3.0.0
tensorboard            1.15.0
tensorflow-estimator   1.15.1
tensorflow-gpu         1.15.4
termcolor              1.1.0
threadpoolctl          3.1.0
typing_extensions      4.1.1
urllib3                1.26.15
webcolors              1.11.1
websocket-client       1.3.1
Werkzeug               1.0.1
wheel                  0.30.0
wrapt                  1.12.1
zipp                   3.2.0
```
**The operating system you're using: Ubuntu 18.04.5**
**The output of `python --version`: 3.6.9**
### Additional context
swagger-spec-validator>2.7.6 requires Python3.7
```
pip install swagger-spec-validator==2.7.6
```

**Comment by Blaizzy** [comment]
Let me know if this helps you :)

**Comment by SiddhantSadangi** [comment]
Hello @nilsmechtel ,

Can you try installing `swagger_spec_validator==2.7.6`? 
Importing neptune should work post that.

Please let me know if it doesnt.

**Comment by nilsmechtel** [comment]
Yes, it does.

**Comment by SiddhantSadangi** [comment]
@nilsmechtel - glad; thanks for the confirmation!

Closing this issue for now, but please don't hesitate to contact us in case you ever need any help or have suggestions :)
