### ISSUE TITLE
NPT-13271: neptune does not restrict the version of the dependency typing_extensions

### ISSUE THREAD

**Issue by fchavat** [neptune-ai/neptune-client#1335]
### Describe the bug
When importing neptune get the error
`ImportError: cannot import name 'ParamSpec' from 'typing_extensions'`
### Reproduction
Before installing neptune, install the dependency `typing_extensions<3.10.0`, then install neptune, and try to import it
### Expected behavior
Should import it, since the install of the neptune dependency didn't throw any conflict.
### Additional context
The method `ParamSpec` was introduced in `typing_extension==3.1.0` so that's why it fails when we previously have installed the dependency on a previous version. But neptune dependency doesn't have this version restriction so It won't complain.
Maybe it should be added as a restriction to neptune?

Thank you for the work on neptune.
Cheers

**Comment by Blaizzy** [comment]
Hi @fchavat 

Prince here,

Thanks for reaching out!

Let me check with the team and come back to you

**Comment by Blaizzy** [comment]
Hi @fchavat 

The devs recommend that you install typing_extension>=3.1.0. 

Let me know if this works for you.

**Comment by fchavat** [comment]
Exactly, this is what I have been doing. But don't you consider that this restriction in version should be included in the package of neptune? Since previous versions don't have the method neptune is using.

Also, I have a typo, the version in which `ParamSpec` was introduced is `3.10.0`, not `3.1.0`.

The main reason I posted that is that having neptune needing typing_extensions>=3.10.0 don't let you use tensorflow 2.6.2 (in the same environment) because TF==2.6.2 needs typing_extensions<=3.7.4.3 so it would be great to recognize that through a conflict in the pip install and not from debugging the failure you get trying to use both after installing them without conflict.

Outside of that, I want to say that I have been using neptune for the previous months and it has been a great tool for me to track the work I'm doing. Thank you!

**Comment by Blaizzy** [comment]
Hey @fchavat 

I understand. I spoke with the devs, and they said we have a permanent solution for this issue in our roadmap. However, there is no ETA on it yet.

I'm glad that you have been using neptune to track your experiments. Could you share some of the areas and tasks you are working on?
