### ISSUE TITLE
BUG: Lightning Integration ModuleNotFoundError

### ISSUE THREAD

**Issue by tarlen5** [neptune-ai/neptune-client#1340]
### Describe the bug
I'm just trying to test out Neptune, attempting to run the basic MNIST example on my EC2 instance, following the [Lightning Integration guide](https://docs.neptune.ai/integrations/lightning/#lightning-integration-guide), using the same code as the Google Colab notebook, except swapping out the API Key given for my own (and my own project just created).
### Reproduction
I expect to run the [Google Colab notebook](https://colab.research.google.com/github/neptune-ai/examples/blob/main/integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb) on my EC2 instance **but replacing the API Key with my own**. I created a file, `main.py` (contents given below) instead of running the notebook, and invoked it at the command line in my anaconda environment using `python main.py`:

```
import os

import numpy as np
import torch
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.loggers import NeptuneLogger
from sklearn.metrics import accuracy_score
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import MNIST

params = {
    "batch_size": 2,
    "lr": 0.1,
    "max_epochs": 2,
}


# (neptune) define LightningModule with logging (self.log)
class MNISTModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = F.cross_entropy(y_hat, y)
        self.log("metrics/batch/loss", loss, prog_bar=False)

        y_true = y.cpu().detach().numpy()
        y_pred = y_hat.argmax(axis=1).cpu().detach().numpy()
        acc = accuracy_score(y_true, y_pred)
        self.log("metrics/batch/acc", acc)

        return {"loss": loss, "y_true": y_true, "y_pred": y_pred}

    def training_epoch_end(self, outputs):
        loss = np.array([])
        y_true = np.array([])
        y_pred = np.array([])
        for results_dict in outputs:
            loss = np.append(loss, results_dict["loss"])
            y_true = np.append(y_true, results_dict["y_true"])
            y_pred = np.append(y_pred, results_dict["y_pred"])
        acc = accuracy_score(y_true, y_pred)
        self.log("metrics/epoch/loss", loss.mean())
        self.log("metrics/epoch/acc", acc)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=params["lr"])


# init model
mnist_model = MNISTModel()

# init DataLoader from MNIST dataset
train_ds = MNIST(
    os.getcwd(), train=True, download=True, transform=transforms.ToTensor()
)
train_loader = DataLoader(train_ds, batch_size=params["batch_size"])

neptune_logger = NeptuneLogger(
    api_key="<MY_API_KEY>,
    project="<MY_PROJECT>",
    tags=["simple-test"],
    log_model_checkpoints=False,
)


# (neptune) initialize a trainer and pass neptune_logger
trainer = Trainer(
    logger=neptune_logger,
    max_epochs=params["max_epochs"],
)

neptune_logger.log_hyperparams(params=params)

trainer.fit(mnist_model, train_loader)
```

### Expected behavior
I expected the file to run to completion, just as it did in the Colab notebook.
### Traceback
> Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from pytorch_lightning import LightningModule, Trainer
  File "/home/ubuntu/miniconda3/envs/test-neptune/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ubuntu/miniconda3/envs/test-neptune/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 29, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/ubuntu/miniconda3/envs/test-neptune/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/ubuntu/miniconda3/envs/test-neptune/lib/python3.8/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/ubuntu/miniconda3/envs/test-neptune/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 62, in <module>
    from pytorch_lightning.loggers import Logger
  File "/home/ubuntu/miniconda3/envs/test-neptune/lib/python3.8/site-packages/pytorch_lightning/loggers/__init__.py", line 20, in <module>
    from pytorch_lightning.loggers.neptune import NeptuneLogger  # noqa: F401
  File "/home/ubuntu/miniconda3/envs/test-neptune/lib/python3.8/site-packages/pytorch_lightning/loggers/neptune.py", line 40, in <module>
    from neptune.new.run import Run
ModuleNotFoundError: No module named 'neptune.new.run'

### Environment
**The output of `pip list`:**
```
Package                  Version
------------------------ ----------
absl-py                  1.4.0
aiohttp                  3.8.4
aiosignal                1.3.1
arrow                    1.2.3
async-timeout            4.0.2
attrs                    23.1.0
blinker                  1.6.2
boto3                    1.26.130
botocore                 1.29.130
bravado                  11.0.3
bravado-core             5.17.1
brotlipy                 0.7.0
cachetools               5.3.0
certifi                  2023.5.7
cffi                     1.15.1
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.3
cryptography             40.0.2
filelock                 3.12.0
fqdn                     1.5.1
frozenlist               1.3.3
fsspec                   2023.5.0
future                   0.18.3
gitdb                    4.0.10
GitPython                3.1.31
google-auth              2.17.3
google-auth-oauthlib     1.0.0
grpcio                   1.54.0
idna                     3.4
importlib-metadata       6.6.0
importlib-resources      5.12.0
isoduration              20.11.0
Jinja2                   3.1.2
jmespath                 1.0.1
joblib                   1.2.0
jsonpointer              2.3
jsonref                  0.2
jsonschema               4.17.3
lightning-utilities      0.8.0
lit                      16.0.3
Markdown                 3.4.3
MarkupSafe               2.1.2
monotonic                1.5
mpmath                   1.3.0
msgpack                  1.0.5
multidict                6.0.4
neptune-client           0.16.18
networkx                 3.1
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
packaging                23.1
pandas                   2.0.1
Pillow                   9.5.0
pip                      23.1.2
pkgutil_resolve_name     1.3.10
protobuf                 3.20.1
psutil                   5.9.5
py3nvml                  0.2.6
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycparser                2.21
pyDeprecate              0.3.2
PyJWT                    2.6.0
pyOpenSSL                23.1.1
pyrsistent               0.19.3
PySocks                  1.7.1
python-dateutil          2.8.2
pytorch-lightning        2.0.2
pytz                     2023.3
PyYAML                   6.0
requests                 2.29.0
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3987                  1.3.8
rsa                      4.9
s3transfer               0.6.1
scikit-learn             1.2.2
scipy                    1.10.1
setuptools               67.7.2
simplejson               3.19.1
six                      1.16.0
smmap                    3.0.5
swagger-spec-validator   3.0.3
sympy                    1.11.1
tensorboard              2.13.0
tensorboard-data-server  0.7.0
threadpoolctl            3.1.0
torch                    2.0.1
torchmetrics             0.11.4
torchvision              0.15.2
tqdm                     4.65.0
triton                   2.0.0
typing_extensions        4.5.0
tzdata                   2023.3
uri-template             1.2.0
urllib3                  1.26.15
webcolors                1.13
websocket-client         1.5.1
Werkzeug                 2.3.4
wheel                    0.40.0
xmltodict                0.13.0
yarl                     1.9.2
zipp                     3.15.0

```
**The operating system you're using:**
Ubuntu
**The output of `python --version`:**
Python 3.8.16
### Additional context
I followed exactly the ["Before you start instructions"](https://docs.neptune.ai/integrations/lightning/#before-you-start) to set up an account and project. No matter what version of pytorch-lightning I tried, I'm still getting this or similar errors. I post here the error from pytorch-lightning 2.0.2 as you can see in my `pip list` output.

**Comment by SiddhantSadangi** [comment]
Hey @tarlen5 ,

We tried to recreate the issue from our end. It looks like you previously had both `neptune` and `neptune-client` installed in your environment and then uninstalled just `neptune`.

Can you try uninstalling and reinstalling `neptune-client`? That resolved the error at our end and should hopefully work for you as well.

**Comment by tarlen5** [comment]
Interesting, this worked, thank you! I thought I did that already. Just to be explicit, what I did was:

```bash
pip uninstall neptune-client
pip install "neptune-client<1.0.0"
```

And everything worked. I can now view my results on the neptune project page I set up. Thanks again!

**Comment by SiddhantSadangi** [comment]
Glad to be of help! :)

I am closing this issue, but please do not hesitate before reaching out to us with any questions or suggestions you might have.

Have a great day!
