### ISSUE TITLE
Feature Request: update to Lightning 2.0

### ISSUE THREAD

**Issue by mrembalski** [neptune-ai/neptune-client#1349]
Currently Neptune does not support Pytorch Lightning 2.0 and that seems like a major drawback. 
- The documentation is based on `pytorch_lightning` and not `lightning`. 
- The Lightning logger checks if `neptune-client` package is installed.

**Comment by SiddhantSadangi** [comment]
Hello @mrembalski ,

Support for Neptune 1.0 was included in PyTorch-lightning v1.9.5, but we missed the v2.0 branch cut off. We should be included in the Lightning v2.1 release. However, the ETA will depend on their release cycles.
If you do not want to wait for the official release, you can install Lightning directly from git.

Please let me know in case you need any help with this.

**Comment by mrembalski** [comment]
This is more of an issue saying that the documentation is outdated and Lightning ensures that neptune is used through `neptune-client` package (which will also be outdated). I managed to make it work, but the documentation in its current state may be a problem for newcomers.

**Comment by SiddhantSadangi** [comment]
The updated documentation has been drafted and is ready to be published as soon as Lightning 2+ includes Neptune 1+ :)
We are holding off publishing it before as that might lead to some confusion for people using Lightning >1.9.5, <2.1.

Can you also share how you managed to make it work? Did you install Lightning from GitHub or downgrade it to v1.9.5?

**Comment by mrembalski** [comment]
Lightning works with `neptune-client` package, but fails when you try to use `neptune`.

Please keep the `neptune-client` package updated at least until Lightning's next release or something - that way people can both use most recent Lightning & Neptune.

**Comment by SiddhantSadangi** [comment]
> Lightning works with `neptune-client` package, but fails when you try to use `neptune`.

Yes, this should be fixed with Lightning release 2.1 which would support `neptune>1.0`

> Please keep the neptune-client package updated at least until Lightning's next release or something - that way people can both use most recent Lightning & Neptune.

Currently both `neptune` and `neptune-client` are at `1.2.0`. The latest `pytorch-lightning` (2.0.2) supports the latest `neptune-client`.
Can you share your versions of the `neptune-client` and `pytorch-lightning`?

**Comment by SiddhantSadangi** [comment]
Hello @mrembalski ,

I wanted to share some good news. Lightning v2.0.4 now supports Neptune v1.0+ 🎉 

You can find our updated Lightning integration guide [here](https://docs.neptune.ai/integrations/lightning/).
I am also sharing our [upgrade guide to Neptune v1.0+](https://docs.neptune.ai/setup/neptune-client_1-0_release_changes/) to help you upgrade from `neptune-client` to `neptune`.

I hope this helps. Please let me know if you need any other support 🙏
