### ISSUE TITLE
Feature Request: Allow disabling git_ref by passing False

### ISSUE THREAD

**Issue by wouterzwerink** [neptune-ai/neptune-client#1394]
### Is your feature request related to a problem? Please describe.
Having to pass `git_ref=neptune.types.GitRef.DISABLED` is unintuitive compared to just passing `git_ref=False`. It also requries a wrapper function to be used with hydra.utils.instantiate.

### Describe the solution you'd like
Allow `git_ref=False` as a simple way of disabling the git_ref

**Comment by SiddhantSadangi** [comment]
Hey @wouterzwerink ,

We just released [neptune v1.5.0](https://github.com/neptune-ai/neptune-client/releases/tag/1.5.0) with this feature included 🚀 

Please let me know if this works for you 🤗
