### ISSUE TITLE
DOCS: Incorrect example in model registry docs

### ISSUE THREAD

**Issue by d13g0** [neptune-ai/neptune-client#1414]
### Describe the bug
Incorrect example in the documentation:
https://docs.neptune.ai/model_registry/registering_model/#registering-a-model

```
import neptune

model = neptune.init_model(
    model="CLS-PRE",  # Your model ID here
)

```

### Reproduction
Run the code example

### Expected behavior
it creates a model

### Traceback
```
  File "<ipython-input-3-82f99b284b2f>", line 1, in <module>
    neptune.init_model(model='test-model')
TypeError: Model.__init__() got an unexpected keyword argument 'model'
```
### Environment
**The output of `pip list`:**
```
neptune                   1.4.1
neptune-notebooks         0.9.3
neptune-pytorch           1.0.1

```
**The operating system you're using:**
MacOS
**The output of `python --version`:**
Python 3.10.12

### Additional context
Just trying to test the new model registry ?

**Comment by SiddhantSadangi** [comment]
Hello @d13g0 ,

Thanks for bringing this to our attention. This is indeed incorrect in the docs, and we will get this fixed.

Meanwhile, you can use the below syntax to create a new model:

```python
model = neptune.init_model(
    key="CLS",  # Your model key here
)
```

Here's the API reference for `init_model()`: https://docs.neptune.ai/api/neptune/#init_model

**Comment by SiddhantSadangi** [comment]
Hey @d13g0 !,

We've corrected the docs: https://docs.neptune.ai/model_registry/registering_model/#registering-a-model

Thanks again for reporting this 🤗

**Comment by d13g0** [comment]
Thank you ! Btw, Ioving the updates in the website and the docs subdomain. Looking sharp! 🚀
