### ISSUE TITLE
BUG: AttributeError: Can't pickle local object 'NeptuneLogger.add_visualization_hook.<locals>.hook

### ISSUE THREAD

**Issue by d13g0** [neptune-ai/neptune-client#1415]
### Describe the bug
I am trying to do `torch.save(model, "filename.pth")`
### Reproduction
I have a `NeptuneLogger` with this configuration:
```

 npt_logger = NeptuneLogger(
        run=run,
        model=model,
        base_namespace='neptune_logger',
        log_model_diagram=True,
        log_gradients=True,
        log_parameters=True,
        log_freq=batch_size
    )
```
### Expected behavior
I was expecting to save the pytorch model

### Traceback
AttributeError: Can't pickle local object 'NeptuneLogger.add_visualization_hook.<locals>.hook'

### Environment
**The output of `pip list`:**
```
neptune                   1.4.1
neptune-notebooks         0.9.3
neptune-pytorch           1.0.1

```
**The operating system you're using:**
MacOS
**The output of `python --version`:**
3.10.12
### Additional context

I want to log pytorch model in a `model_version` using:

```
model_version['weights'].upload("weights_file.pth")
```

I wish there was a way to simply pass the `model` object to avoid saving to disk first. This is inconvenient and I think this bug is a side effect of saving a pytorch model with the logger as an 'observer' ??

**Comment by SiddhantSadangi** [comment]
Hello @d13g0 ,

Since `NeptuneLogger` adds unserializable hooks to the `model`, you should save the state of the model using [`state_dict()`](https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.state_dict):
```python
torch.save(model.state_dict(), "filename.pth")
```

Currently, there is no way of passing just the `model` to upload it. To avoid writing it to disk, you can save it and upload it from an in-memory object as follows:
```python
from neptune.types import File
from io import BytesIO

bytes_io = BytesIO()

torch.save(model.state_dict(), bytes_io)
model_version["weights"].upload(File.from_stream(bytes_io))
```

Please let me know if this works for you 🙏

**Comment by d13g0** [comment]
Thanks @SiddhantSadangi 

I think that would work since you are only saving the weights and biases (state_dict). However, the question of saving the whole object remains. 

I used this "dirty" trick:

```
model. _forward_hooks = {}
```
before invoking `torch.save` and it works! :-)

**Comment by SiddhantSadangi** [comment]
Hey @d13g0 ,
Removing the hooks is also an option, but be sure to do it at the end of the script, as adding the hooks back to the model is a pain :D

**Comment by SiddhantSadangi** [comment]
We are also checking if we can make the hooks serializable, so that you won't have to remove them before saving a model.

**Comment by SiddhantSadangi** [comment]
I am closing this issue now, but please feel free to reopen it if you need assistance with this or create a new issue if we can help with something else.

Have a great day! 🌞
