### ISSUE TITLE
BUG: Inconsistent behaviour betweeen `init_model` and `init_model_version`

### ISSUE THREAD

**Issue by d13g0** [neptune-ai/neptune-client#1416]
### Describe the bug
I create a model with:
```
mod = neptune.init_model(
            key='MODEL',
            project = 'PROJECT',
            name = 'My Model'
        )
```

Then, I want to create a version of this model with:
```
mod_version = neptune.init_model_version(
            model='MODEL',
            project='PROJECT'

        )
```

I get this error:
```
311, in get_metadata_container
    raise MetadataContainerNotFound.of_container_type(
neptune.exceptions.ModelNotFound: Model <<user>>/PROJECT/MODEL not found.
```

However, if I add the "key" to the model name like this (e.g. 'PRE'):

```
mod_version = neptune.init_model_version(
            model='PRE-MODEL',
            project='PROJECT'
        )
```

Then the model version is created. 

### Expected behavior
Since I am providing the `project` parameter to create the model version, the code should not fail, as the proper prefix (key) can be inferred from the project name.

### Traceback
If applicable, add traceback or log output/screenshots to help explain your problem.
### Environment
**The output of `pip list`:**
```
neptune                   1.4.1
neptune-notebooks         0.9.3
neptune-pytorch           1.0.1

```
**The operating system you're using:**
MacOS
**The output of `python --version`:**
3.10.12

### Additional context
None

**Comment by Blaizzy** [comment]
Hi @d13g0 

This happens because the model version method takes a combination of `project_key` and `model_key` as the model argument.
Where `project_key` can be fetched from a neptune object ID (i.e., runs, project, etc.).

**Example**:
```python

project = "workspace/project_name"
run = neptune.init_run(project=project)

# (Neptune) Initializing a Model and Model version
model_key = "PIPELINES"
project_key = run["sys/id"].fetch().split("-")[0]

# (Neptune) Creating a new model
model = neptune.init_model(key=model_key, project=project)
model.wait()

# (Neptune) Creating a new model version
model_version = neptune.init_model_version(model=f"{project_key}-{model_key}")
```

**Comment by d13g0** [comment]
@Blaizzy I think what you are saying is sensible. However, I am giving you the perspective of a noob (me) trying the framework for the first time. The simpler the better for adoption, IMHO. Thanks!

**Comment by SiddhantSadangi** [comment]
Hey @d13g0 ,

Your suggestion actually makes total sense!
We have discussed this internally in the past as well and will be processing your suggestions as a feature request :)
