### ISSUE TITLE
Additional `development` model stage leve

### ISSUE THREAD

**Issue by SebastianScherer88** [neptune-ai/neptune-client#1493]
### Is your feature request related to a problem? Please describe.

In my team, have three environments/K8s clusters into which we deploy our models:
- dev
- stage
- production

[there is currently no `development` level in the model version `STAGE` attribute.](https://github.com/neptune-ai/neptune-client/blob/04bd984268104ea990d8d28bccdb77408f574c6b/src/neptune/types/model_version_stage.py#L21)

### Describe the solution you'd like

it would be useful to have an additional model stage level of `development` (`staging` and `production` already exist) to be able to consistently use the `STAGE` model attribute column to track a model's deployment state.

### Describe alternatives you've considered

Atm we use tags to capture a model's deployment state. this also has the benefit of being able list multiple deployment environments for those model versions that are deployed in, say, `development` _and_ `stage` at the same time in the process of promoting them to production.

**Comment by SiddhantSadangi** [comment]
Hey @SebastianScherer88 👋 

I've forwarded this to the product team as a feature request.

Meanwhile, would it be possible for you to use the _Tags_ field to monitor the model version stage? You can add your custom stages, and update them from the UI or the API. 

Here is the API reference showing how you can do it: https://docs.neptune.ai/api/field_types/#stringset

Please let me know if this works for you while we process the feature request.

**Comment by SebastianScherer88** [comment]
Hi there,

Thanks for the quick reply! Also thanks for the docs reference - we are indeed using customised tags to manage the deployment status of a given model version for now 😊

So no blockers, but I though I might as well create a ticket with some feedback on that one missing stage level while I’m at it.

Regards,

Sebastian

**Comment by michalsustr** [comment]
Hi @SebastianScherer88 , Michal from https://minfx.ai - you can do arbitrary HashMap of state on our runs, and have it map how you like. Please take a look at our project
