### ISSUE TITLE
How to handle with the ConnectionResetError

### ISSUE THREAD

**Issue by ganfisher** [neptune-ai/neptune-client#1878]
Hello, I'm a beginner of neptune-client, and the version of 1.10.4 is used. I'm trying to revise the code of "genetic expert guided learning" based on the legacy api. When I just update the codes about neptune api the benchmark program can be completed normally. However, after further introducing my revised code of the scoring function, the benchmark program raises a ConnectionResetError halfway. I have set NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE=True, but the problem is still unresolved.
What are the possible causes of the error? How should I handle with it?

**Comment by SiddhantSadangi** [comment]
Hey @ganfisher 👋 

﻿Thank you for reporting this issue! Could you please provide us with more details:

### 1.  Describe the bug.
﻿A clear and concise description of the problem you're experiencing. ﻿

### 2. Reproduction﻿
Please provide steps to reproduce the issue or code snippet in as much detail as possible.

### 3. Expected behavior
﻿A clear and concise description of what you expected to happen.﻿

### ​﻿﻿​﻿4. Traceback
﻿If applicable, add traceback or log output/screenshots to help explain your problem.﻿

### 5. Environment info
﻿**The output of `pip list`:** 
﻿**The operating system you're using:** 
**The output of `python --version`:**﻿ 

### 6. Additional context
﻿Add any other context about the problem here.

**Comment by ganfisher** [comment]
Hello, sorry for the answer delay. I have migrated the old API codes to the new API codes, and the ConnectionResetError does not appear again. However, the running might be stuck after a few epoches, and no exceptions are raised. The running stuck is like the phenomenon described in issue #1151 , but neptune logger and Pytorch Lightning are not explicitly called in my case. I'm still trying to handle the problem by myself.

**Comment by ganfisher** [comment]
> Hello, sorry for the answer delay. I have migrated the old API codes to the new API codes, and the ConnectionResetError does not appear again. However, the running might be stuck after a few epoches, and no exceptions are raised. The running stuck is like the phenomenon described in issue #1151 , but neptune logger and Pytorch Lightning are not explicitly called in my case. I'm still trying to handle the problem by myself.

I will try the offline mode first.

**Comment by SiddhantSadangi** [comment]
Hey @ganfisher ,

Please let me know if the offline mode works.
If it does, the amount of metadata logged asynchronously might be too much for your network.

**Comment by ganfisher** [comment]
> Hey @ganfisher ,
> 
> Please let me know if the offline mode works. If it does, the amount of metadata logged asynchronously might be too much for your network.

Yeah, the offline running could finish successfully. However, HTTPError could be raised from time to time, if I try to synchronise the offline results with "neptune sync". Considering that the "ring" symbol meaning "synchronising" exists, the HTTPError may not matter?

**Comment by ganfisher** [comment]
Is there any way to visualize the logged metadata locally?

**Comment by ganfisher** [comment]
> > Considering that the "ring" symbol meaning "synchronising" exists, the HTTPError may not matter?
> 
> Could you post a screenshot of the traceback?
> 
> > Is there any way to visualize the logged metadata locally?
> 
> No, unfortunately.
Sure, the screenshots are posted here.
![{816885AB-1459-4181-9E41-AFC2BE2C4073}](https://github.com/user-attachments/assets/2939a1c6-e4bf-43ab-aebe-b139af8d4c1c)
![{FE9F3F61-1EAE-4A79-A92F-FB956FFD1692}](https://github.com/user-attachments/assets/84680040-d44d-4969-beb1-2a1364d6e982)

**Comment by SiddhantSadangi** [comment]
Yeah, that's fine.
As long as the sync completes successfully, there should not be any cause for concern ✅

**Comment by ganfisher** [comment]
> Yeah, that's fine. As long as the sync completes successfully, there should not be any cause for concern ✅

Thanks, I will close the issue, if all the data can be uploaded successfully.

**Comment by ganfisher** [comment]
> Yeah, that's fine. As long as the sync completes successfully, there should not be any cause for concern ✅

Thank you for your help, all the metadata can be uploaded with enough time.
