### ISSUE TITLE
Feature Request: Make `pandas` optional for SDK v2

### ISSUE THREAD

**Issue by antoinebrl** [neptune-ai/neptune-client#1894]
Hi! While you are working on a new major version for the Neptune SDK, would it be good opportunity to reconsider the dependency on `pandas`? its use seems to be limited to only a couple of processing functions so maybe it can be removed or be mark as optional dependency.

**Comment by SiddhantSadangi** [comment]
Hey @antoinebrl 👋 

We've already removed `pandas` and many other dependencies from [`neptune-scale`](https://github.com/neptune-ai/neptune-client-scale). ✂️ 

`neptune-scale` is the v2 of `neptune`.

![image](https://github.com/user-attachments/assets/fc81d18a-eb39-442a-9bbf-629e996b9e37)

**Comment by michalsustr** [comment]
Hi @antoinebrl , Michal from https://minfx.ai - please have a look, we are taking dependency hell problems very seriously, and will make future minfx package slim. No protobufs anywhere or any such non-sense!
