### ISSUE TITLE
Instantiate estimator from best parameters

### ISSUE THREAD

**Issue by hugwi** [neptune-ai/neptune-client#200]
Hello!  

First off, I absolutely love the interface and easy integration/documentation you provide!! And hats off for @jakubczakon whom provided with great tutorials! However I stumbled on a problem when retrieving the best results. I saved artifacts but I'm not successful in retrieving them.

```python
>>> exp = project.get_experiments('BAY-59')[0]
>>> artifacts = exp.download_artifacts()
>>> print(artifacts)
None
```
And if i try by retrieving the best results by _project.get_leaderboard('BAY-59')_ the results is a string.

**Comment by kamil-kaczmarek** [comment]
Hey @hugwi,

Thanks for your kind words :)

Just a quick note: `download_artifact()` - downloads your data to your disk ([docs](https://docs.neptune.ml/neptune-client/docs/experiment.html#neptune.experiments.Experiment.download_artifacts)).

`None` is returned as a result of that method.
Check `destination_dir` (see docs for help) - your data is there.

Best,
Kamil

**Comment by aniezurawski** [comment]
Hi @hugwi 

1. `download_artifacts()` does not return any value. It downloads artifact files to your disk.
See https://docs.neptune.ml/neptune-client/docs/experiment.html?highlight=download_artifact

2. `get_leaderboard` returns `pandas.core.frame.DataFrame`. Maybe try to use `get_experiments` instead.

**Comment by hugwi** [comment]
Haha, ok. Giving you cred for documentation and then not reading through it thoroughly enough :D But if I understand it correctly. If I'm working in notebook (colab) then I need to download it and then load it?

**Comment by hugwi** [comment]
It would be nice if you could skip the manual labour of donwloading it, unzipping it unpickle it if your working with it in a notebook :)

**Comment by jakubczakon** [comment]
You can actually use the helper from neptune-contrib `get_pickled_artifact`:
https://neptune-contrib.readthedocs.io/user_guide/api/utils.html#neptunecontrib.api.utils.get_pickled_artifact

```python
from neptunecontrib.monitoring.utils import get_pickled_artifact

results = get_pickled_artifact(experiment, 'results.pkl')
```

Does that sound good @hugwi.

**Comment by hugwi** [comment]
Sounds great. I installed neptune-contrib with pip but throwing me this exception. (in colab)
```
ImportError                               Traceback (most recent call last)
<ipython-input-7-c8e1fef06f48> in <module>()
----> 1 from neptunecontrib.monitoring.utils import get_pickled_artifact
      2 
      3 results = get_pickled_artifact(experiment, 'results.pkl')

ImportError: cannot import name 'get_pickled_artifact'
```

**Comment by jakubczakon** [comment]
Apologies @hugwi this function is in the `api.utils` [here](https://neptune-contrib.readthedocs.io/user_guide/api/utils.html#neptunecontrib.api.utils.get_pickled_artifact)

```python
from neptunecontrib.api.utils import get_pickled_artifact
```

**Comment by pkasprzyk** [comment]
I'm closing this issue since there was no response from user in over a year.
