### ISSUE TITLE
Asking for `experiment.name` takes a long time

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#210]
Some properties of the experiments need to be downloaded from the backend. I understand this logic but this is impractical. My case:

I have 1000 experiments and want to download some of them and filter them by name but calling `experiment.name` requires 1000 calls to the server, which takes ages. This is a pain. Another server call is when I ask for `experiment.get_properties()` and another for `experiment.state`. Thus 3000 requests to the server just for such simple data.

I think, it would be perfectly reasonable to make `get_experiments()` download those data and keep them static and if this is too convoluted then, please at least allow to filter experiments by name in `get_experiments()`.

**Comment by pitercl** [comment]
Hi @wjaskowski !

Would using `get_leaderboard()` instaead of `get_experiments()` solve this for you?
It returns a Pandas DataFrame with all of experiment's info right there (no server calls).

https://docs.neptune.ai/neptune-client/docs/project.html#neptune.projects.Project.get_leaderboard

**Comment by wjaskowski** [comment]
Perfect - much quicker. Thx!
