### ISSUE TITLE
Offline mode usage

### ISSUE THREAD

**Issue by yngtodd** [neptune-ai/neptune-client#214]
I have a machine whose compute nodes have no access to the internet. Is it possible to use the offline mode during compute and load the results the the web interface after the compute job is finished?

**Comment by kamil-kaczmarek** [comment]
Hey @yngtodd,

If you turn on an offline mode, right now you will be unable to load results later.

@pitercl can we introduce it somehow?

**Comment by yngtodd** [comment]
I could imagine first storing all of our results in a database on our machine. Then I could have a post-processing step that would loop through the results and push things to Neptune. Not having internet access on our compute nodes would basically make it a two step process, yeah?

**Comment by kamil-kaczmarek** [comment]
Hey @yngtodd,

Thanks for the idea -> again @pitercl is better person to take this.

Cheers,
Kamil

**Comment by Herudaio** [comment]
Hey @yngtodd !

We've recently released a new version of Neptune! You can read all about it in [the release blogpost](https://neptune.ai/blog/neptune-new), but in particular [offline mode](https://docs.neptune.ai/you-should-know/connection-modes#offline) may be of an interest to you :)

**Comment by yngtodd** [comment]
Thank you! That is great news!

**Comment by Herudaio** [comment]
Np. - closing the issue, if anything new pops up - let us know!

**Comment by Zacchaeus14** [comment]
@Herudaio Hi, I was using offline mode in a slurm computation node, however, all logs are not appearing on the dashboard even if call `neptune sync`. There is just an empty run on the dashboard. Can you help me? Thanks.

**Comment by kamil-kaczmarek** [comment]
Hey @Zacchaeus14,

When you work in the offline mode, neptune dump the metadata to `.neptune` directory. In your case data is placed in the computation nodes.
Can you try to run `neptune sync` on those computation nodes?
If you already did that, please describe what metadata do you log?
