### ISSUE TITLE
allow neptune.send_metric to take "step" in addition to timestamp

### ISSUE THREAD

**Issue by hadyelsahar** [neptune-ai/neptune-client#235]
I have some metrics that is being logged each 1 step and other metrics that are logged each 10 time steps unfortunately this makes the graphs non-comparable on the interface. 

Can we allow the `neptune.send_metric` to take step count. So when displaying them the both graphs become comparable?

Thanks

**Comment by pitercl** [comment]
Hi @hadyelsahar!

Have you tried using the `x` argument of `neptune.send_metric`?

**Comment by Herudaio** [comment]
@hadyelsahar in the [updated Neptune API](https://neptune.ai/blog/neptune-new) we actually cleared it up a bit - it's now explicitly called `step` and `timestamp` (See [API Reference](https://docs.neptune.ai/api-reference/field-types#log))
