### ISSUE TITLE
Failed to send channel value: SSL certificate validation failed.

### ISSUE THREAD

**Issue by Jonas1312** [neptune-ai/neptune-client#241]
Hi,

Just discovered neptune.ai and it's really great!

I have the following error:
`Failed to send channel value: SSL certificate validation failed. Set NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE environment variable to accept self-signed certificates.`

Even if I set `NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE` in my `bashrc` neptune-client still throws this error.

.bashrc:
`export NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE=True`

python:
```python
Python 3.7.7 (default, Mar 10 2020, 15:16:38) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getenv("NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE")
'True'
>>> `
```

System:
ubuntu 18.04
neptune-client 0.4.116
python 3.7.7

**Comment by szymon-kuklewicz** [comment]
Hi,

We've prepared new version of neptune-client 0.4.117 that should help you resolve the issue. With new version, when such exception occurs, full traceback of the exception should be logged and we will be to able to fix the issue once we know more details.

Please update your neptune-client and try again.

**Comment by Jonas1312** [comment]
Thanks for the update

However I don't know what happened but I can't reproduce the error today... I will reopen this issue if it occurs again.
