### ISSUE TITLE
Download artifact from a previous experiment??

### ISSUE THREAD

**Issue by justAyaan** [neptune-ai/neptune-client#248]
Hi.. 
1)	I have created an experiment
2)	I logged a '.csv' file to that experiment and then stopped it(experiment.stop())
3)	I now need to access that file by code... 

something like, loading the experiment and get the output files by ‘experiment.download_artifact’..
The code might look like this,:-

`previous_experiment = neptune.load_experiment(id = 'SAN-1')# loading a previously made experiment`
`my_csv = previous_experiment.download_artifact('xyz.csv')`

 Is it possible??

**Comment by PiotrJander** [comment]
Perhaps the following snippet will help, let us know if it doesn't!

```python
import neptune

project = neptune.init()

# create your experiment and send an artifact
old_exp = neptune.create_experiment()
old_exp.send_artifact("test.txt")

# save the id of that experiment
old_exp_id = old_exp.id

#stop the experiment
old_exp.stop()


# retrieve that experiment by id
new_exp = project.get_experiments(old_exp_id)[0]

# download artifact
new_exp.download_artifact("test.txt", "downloads")
```

**Comment by justAyaan** [comment]
thanks!! i had previously come till project.get_experiments(old_exp_id) but i noticed that it returned a string due to which i had lost hope but thanks!!

**Comment by PiotrJander** [comment]
Glad it helped, let us know if you need more help or feel free to close the issue.
