### ISSUE TITLE
Python Logger logs not captured in neptune UI

### ISSUE THREAD

**Issue by richt3211** [neptune-ai/neptune-client#309]
I am just getting started with my first neptune project and am running into a problem with the logger. I haven't seen any information online about this particular problem so I wanted to post it here. 

The following is an example of a project and experiment initialization that passes in a python logger object. 
```python
import logging
import neptune
from src.keys import NEPTUNE_TOKEN
from neptune.experiments import Experiment
neptune.init('richt3211/thesis', api_token=NEPTUNE_TOKEN)

logger = logging.getLogger()

exp = neptune.create_experiment(
name='test log',
description='testing logger',
logger=logger
)

logger.info('Starting experiment')
```

When I run this in a jupyter notebook, the experiment is created, but no logs appear. 
![Screen Shot 2020-11-19 at 1 20 10 PM](https://user-images.githubusercontent.com/19878922/99719877-20324f00-2a6a-11eb-8382-9d4558a3eb96.png)

I believe this is the correct way to capture a python logger in neptune according to the [docs](https://docs.neptune.ai/api-reference/neptune/projects/index.html#neptune.projects.Project.create_experiment). If it's not the docs might need updated to give a clearer example. If it is the correct, way, there may be a bug.

**Comment by PiotrJander** [comment]
Hi @richt3211 , looking at your snippet, I think your problem is with how Python logging woks, not with Neptune.

In Python, each logger has a severity level associated with it. It appears to be Warning / 30 by default.

But you tried logging a message with the Info / 20 level. This is a lower level than your logger's level (Warning) and so the logger will not propagate the logged message to the handlers (i.e. to Neptune).

So try `logger.setLevel('INFO')`. Doing `logger.warning('Starting experiment')` would also work.

Let us know if this helps!

**Comment by richt3211** [comment]
@PiotrJander I added both the logger.setLevel('INFO') and the logger.warning('Starting experiment') and neither of them worked.

**Comment by richt3211** [comment]
I've figured out what the problem is. Neptune is capturing the logs but the ui shows them in the monitoring tab and not the logs tab, so I wasn't aware that they were being captured. 
![Screen Shot 2020-11-23 at 12 28 34 PM](https://user-images.githubusercontent.com/19878922/100006262-76173780-2d87-11eb-8239-0db8e093242c.png)

![Screen Shot 2020-11-23 at 12 28 49 PM](https://user-images.githubusercontent.com/19878922/100006279-7ca5af00-2d87-11eb-96f8-8b3b17f7f410.png)

Putting them in the monitoring tab seems a little unintuitive. Not sure why they aren't showing up in the logs tab.

**Comment by szymon-kuklewicz** [comment]
Hi @richt3211, 

Captured stdout/stderr output from your Python process as well as hardware monitoring (CPU/GPU/RAM charts) were put together to have all automatically retrieved information in one place in distinction of Neptune-specific logs initiated by users. We can speculate that stdout and stderr are logs too, but we think that if you use Neptune, you should log your progress and all your relevant information during the experiment as text/numbers/images using Neptune API for future analysis. This is what is Neptune for. To help you track and analyze progress and outcomes of experiments. We currently do not have any analytics put on stdout/stderr logs, so they are captured and displayed only for monitoring purposes.

If you have more insights why stdout/stderr should be moved to logs, I can suggest it to Neptune's product manager. For now, I'll close this issue.

Thank you.

**Comment by richt3211** [comment]
@szymon-kuklewicz The description in the docs directly conflicts with where the log shows up in the UI. This is the description. 

```
If Python’s Logger is passed, new experiment’s text log (see: log_text()) with name “logger” is created. 
Each time Python logger logs new data, it is automatically sent to the “logger” in experiment. 
As a result all data from Python logger are in the Logs tab in the experiment.
```

It would make sense to me to have the log exist in the Logs tab (...because it's a log). The API allows for a direct integration with an existing logger into Neptune so I think it can be viewed as an actual experiment log rather than just capturing the system output. When I specifically registered a logger with the API I assumed it would show up in the logs tab just as any other specific log would.

**Comment by aniezurawski** [comment]
Hi, I agree it would be more intuitive behaviour. However right now I cannot say if it was designed this way and we have some bug or there is a mistake in docs. Anyway, we will give it a closer look. Thanks for bringing our attention to it.

**Comment by Herudaio** [comment]
@richt3211 We took the feedback into account and in the neptune.new Python API the Python Logger is captured through a [dedicated handler](https://docs.neptune.ai/api-reference/integrations/python-logger). By default, the logs will be captured under `monitoring/python_logger` path, but you can customize it when creating the handler.
