### ISSUE TITLE
NQL Allowing for Space in Field Names

### ISSUE THREAD

**Issue by richt3211** [neptune-ai/neptune-client#343]
I'm trying to use the advanced search option with NQL but am running into an issue trying to write a query for a specific field. My field is named "trained epochs" which is a nice indication to quickly check the progress of a model without looking at the charts. 

I would like to write a query for experiments that only have at least one value for the trained epochs metric. However, because there is a space in the field name, I can't write a query to accomplish this. 

So far I have tried the following queries
```
"trained epochs" > 0
epochs > 0
trained\ epochs > 0 # trying to escape the space character
```

Is it possible to allow for spaces in NQL fields? Another solution would be to have an option to rename the metric so that it is compatible with NQL. If it isn't possible to allow for spaces in NQL, it would be nice to have something in the docs that mentions this for field name creation so that users are encouraged (or even forced) to not have spaces in the metric and log names.

**Comment by aniezurawski** [comment]
Hi @richt3211 

Double quotes `"` are used for string values and single back quotes `` ` `` are used for fields. So your query should be `` `trained epochs` > 0``.
Moreover, renaming fields will be possible in the near future. ;)

**Comment by richt3211** [comment]
@aniezurawski Thank you! This was just what I needed. 

Read through the docs several times and missed the part where it talks about different quotes. Might be a good idea to add a little clause to the fields section of the docs about the backtiks for clarity's sake.
