### ISSUE TITLE
neptune.api_exceptions.InvalidApiKey: The provided API key is invalid.

### ISSUE THREAD

**Issue by pzSuen** [neptune-ai/neptune-client#350]
I copy my API key my "Your API Token" directly,
but I get the error both in Colab and on my computer.
I didn't do anything wrong, I think this may be a bug.

![截图_20201521101550](https://user-images.githubusercontent.com/43957007/102786459-79c7c980-43da-11eb-9b8c-cfb189d7abeb.png)

**Comment by szymon-kuklewicz** [comment]
Issue resolved. Copied token did not match exactly.
