### ISSUE TITLE
Making it possible to get experiment link

### ISSUE THREAD

**Issue by kazet** [neptune-ai/neptune-client#375]
Currently, Project._get_experiment_link() is protected. Is there any reason it should not be used by external code? In our use-case, we save the experiment links internally for future reference - it would be awesome if we wouldn't have to call protected methods for that.

**Comment by Herudaio** [comment]
Hi @kazet! 

Not really, there isn't :) We didn't expect at the start that it would useful to people! It's a good idea and at some point, we will move it to the public API, thanks for the suggestion!

**Comment by Herudaio** [comment]
Hi @kazet !

There is now publicly available method for [fetching run's URL now](https://docs.neptune.ai/api-reference/run#get_run_url) :)
