### ISSUE TITLE
Reseting stderr/stdout

### ISSUE THREAD

**Issue by jwitos** [neptune-ai/neptune-client#398]
Hi!

Thank you for developing this wonderful tool, it has recently been a great help to our team to track experiments.

I was wondering if there is an option to remove stderr/stdout logs from completed experiments? Unfortunately I quickly filled a large portion of available storage by allowing experiments to upload very verbose system logs (20-40MB per experiment). I was hoping to clean the storage by removing those from old experiments.

My first thought was to use `reset_log()`, which uses `USER` ChannelNamespace by default:

https://github.com/neptune-ai/neptune-client/blob/0000cca1d0b9b0f01134c5529c842600d164e1b6/neptune/experiments.py#L878

Changing this to `ChannelNamespace.SYSTEM` allows me to get correct stderr/stdout channel, but ends up in 403 forbidden error.

Is there an option to reset stdout/stderr channels? Would it be possible to allow running `reset_log` on those channels or is it an intentional behavior and the only way to clean the storage is to remove the experiment in full?

**Comment by aniezurawski** [comment]
Hi @jwitos 

Unfortunatelly it is not possible for now.

**Comment by aniezurawski** [comment]
Hi @jwitos 

Unfortunately it is not possible right now. But stay tuned! Some cool changes are coming in general experiments' metadata organization.

**Comment by jwitos** [comment]
Thanks @aniezurawski! Will keep an eye on it.
