### ISSUE TITLE
Misleading error message in project.get_experiments

### ISSUE THREAD

**Issue by mbednarski** [neptune-ai/neptune-client#407]
Hi

When executing `get_experiments` method in `Project`  with incorrect argument (for example typo in `state`) Nepune raises a `neptune.api_exceptions.ServerError: Server error. Please try again later.` which is misleading.

It would be better to get something like `ValueError: incorrect value for parameter state` instead.

Steps to reproduce

~~~
project = neptune.init()
experiments = project.get_experiments(state='succeded')
~~~

neptune-client version: 0.5.1

**Comment by aniezurawski** [comment]
Hi @mbednarski !

Thank you for bringing our attention to this issue. We are already working on some quick fix on server side. And we will pay more attention to proper validation on client side in future. :)
