### ISSUE TITLE
Removing experiments doesn't update storage info

### ISSUE THREAD

**Issue by jwitos** [neptune-ai/neptune-client#409]
Hello,

I was removing a bunch of experiments hoping to free up some space used by my projects, but it looks like removing them doesn't affect the storage usage statistics. Even after e.g. removing all experiments in a sandbox project the storage is still used.

Is that an expected behavior / is storage recalculated every once in a while and this is why I don't see any changes? Is there any way to check the current actual storage used?

**Comment by hubertjaworskineptune** [comment]
Hi,

Removing experiments from Neptune is a three step process -

1. Trash experiment(s)
2. Remove experiments(s) from trash
3. Async cleanup on server side

Note, that if you don't clean your trash, your storage space will not go down

**Comment by jwitos** [comment]
That's embarrassing, I didn't even realize Neptune has a trash & ability to restore 😄. That's very nice and it did work. Sorry to bother you with a ticket!
