### ISSUE TITLE
Directly push multiples metrics to same graph

### ISSUE THREAD

**Issue by yohann84L** [neptune-ai/neptune-client#425]
Is there a way to directly push metrics to the same graph ? 
For example, push `Average Precision - Class 1`, `Average Precision - Class 2`, ..., `Average Precision - Class n` to a graph called `Average Precisions`.
I know we can do it using "Chart's set", but it's kinda annoying to it by hand if we have a lot of metrics.

Thanks !  🙏

**Comment by Herudaio** [comment]
Hi @yohann84L!

Unfortunately, there is currently no option to automatically create such a graph. Good thing is that once you create it the chart set is available for all experiments in the same project. So if those experiments have the same metrics name, it's only a one-time job.

However! We are cooking some things on this topic so you can expect this to be a bit easier to do in near future :)

**Comment by yohann84L** [comment]
Hello @Herudaio,  thanks for the answer! This is of course a good thing to know.
However, I managed to do it with [https://github.com/altair-viz/altair](altair-viz) and then push it to neptune through `neptunecontrib.api.log_chart`.
