### ISSUE TITLE
log_image with numpy array silently produce artefacts if range is outside [0,1]

### ISSUE THREAD

**Issue by abouysso** [neptune-ai/neptune-client#432]
neptune-client version : 0.5.1

When logging numpy array as images, strange behavior is happening (inverted colors and so on...) if data range is outside [0,1], for example with uint8 images. In my opinion this should be forbidden or throw a warning.

**Comment by Herudaio** [comment]
@abouysso thanks for reporting this! 
We will change it so that the behavior is more explicit. When converting to an image through [`File.as_image`](https://docs.neptune.ai/api-reference/field-types#as_image) there will be a warning if the values are outside of range.
