### ISSUE TITLE
Jupyter notebook extension drops API token's trailing punctuation

### ISSUE THREAD

**Issue by christabella** [neptune-ai/neptune-client#502]
In the edge case that my API token ends in `==`, on the Jupyter notebook under the steps to "Activate", the `==` gets truncated/dropped.

My API token ends in `Q==`:
![image](https://user-images.githubusercontent.com/2038751/114484445-d591b900-9c3c-11eb-8855-f66c416eab19.png)

My API token ends in `Q`:
![image](https://user-images.githubusercontent.com/2038751/114484464-db879a00-9c3c-11eb-9c85-8f73dd641c42.png)

This results in the "activate" button not working, as the API token is now invalid.

**Comment by christabella** [comment]
Perhaps this issue should be in the other repo, since it's the apiToken gets passed into getActivationCode():

https://github.com/neptune-ai/neptune-notebooks/blob/273371c4ba04fc0f9fc95a2155e871ccd4a2964a/packages/neptune-extension/src/common/components/activation-modal/ActivationModal.tsx#L46

**Comment by pzurowski** [comment]
Thank you for reporting a bug, we will do our best to resolve it. Sorry for the inconvenience.

**Comment by kierson** [comment]
Hi @christabella 

Are you sure that the token displayed in https://app.neptune.ai/get_my_api_token is exactly the same you pasted into Configuration modal in neptune-notebooks extension? You can check it by click on `N` (Neptune) icon in your notebooks toolbar.

My token also ends with `Q==` and it works just fine in the activation modal.
I've checked our code and we do not escape any characters from the token so it should be exactly the same that you've provided in Configuration.

**Comment by kierson** [comment]
Since there is no reply and no other people reporting the same/similar issues I am closing this one.
Feel free to open new one if problem occurs.
