### ISSUE TITLE
Description doesn't get sent from Jupyter notebook

### ISSUE THREAD

**Issue by christabella** [neptune-ai/neptune-client#503]
When I upload a notebook to Neptune, the title gets sent but the description is dropped from the published snapshot.

**Comment by jakubsy** [comment]
Hello @christabella,

Thank you for your report.

Unfortunately I failed to reproduce your issue.

I think I would need some more information:
1. Whether you're using Jupyter Lab or Jupyter Notebook (+ its version)
2. What is the version of neptune-notebooks
3. What is the url for notebook where we can observe the bug

Could you please contact us via in-app chat (the message bubble in the right bottom corner) or via email (contact@neptune.ai) and provide more details on your setup?

BR,
Jakub

**Comment by pkasprzyk** [comment]
No contact from user for more than 3 months. Closing, @christabella feel free to reopen or create a new issue if you're still having any problems.
