### ISSUE TITLE
sync fails when unsynced run contains unsent NaN

### ISSUE THREAD

**Issue by Sleepwalking** [neptune-ai/neptune-client#504]
One of my past experiments blew up into NaNs after a few hundred epochs, which coincided with a network failure that brought rest of the experiment offline. Later when I tried to call `neptune sync`, the command hits this dead experiment and stops on an exception.

```
----ClientHttpError-----------------------------------------------------------------------

Neptune server returned status 400.

Server response was:
{"code":400,"title":"Malformed JSON request: JSON parse error: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: (PushbackInputStream); line: 1, column: 79]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: (PushbackInputStream); line: 1, column: 79]\n at [Source: (PushbackInputStream); line: 1, column: 67] (through reference chain: java.util.ArrayList[0]->ml.neptune.leaderboard.api.model.operation.OperationDTO[\"logFloats\"]->ml.neptune.leaderboard.api.model.operation.LogFloatsDTO[\"entries\"]->java.util.ArrayList[0])","errorType":"MALFORMED_JSON_REQUEST"}
```

Which prevents me from uploading other unsynchronized runs after this particular malformed one.

Before a bug fix can be made, I wonder if there's a temporary fix/any trick that allows me to directly remove this naughty experiment from the file system?

**Comment by aniezurawski** [comment]
Thanks for your report. We will fix it.

Here's a workaround:
Find internal uuid of your run: `run = neptune.init(run="MYRUN-123"); print(run._uuid)`
Go to directory `cd .neptune/async/<INTERNAL_UUID>/`
You can just remove this directory or you can search for NaNs in `data-*.log` files and replace them by some valid number.

**Comment by aniezurawski** [comment]
Hi again @Sleepwalking 

Actually it turned out that this issue was fixed today earlier. :)

**Comment by Sleepwalking** [comment]
Hi @aniezurawski Thanks for the speedy response! I just upgraded `neptune-client` and saw this fixed. Wonderful work done.
