### ISSUE TITLE
How to not send any source file?

### ISSUE THREAD

**Issue by psinger** [neptune-ai/neptune-client#508]
Even if I specify to not send any source files in the init function, the client sends the main python file to Neptune.

How can I enforce to not send any source files?

**Comment by HubertJaworski** [comment]
Hi!

Have you tries passing an empty array to `source_files` parameter of init?

```
neptune.init(project='workspace/project', api_token=token, source_files=[])
```

It still saves the name of the file under `source_code/entrypoint`, but no content is sent

I'll ask the person responsible for the docs to take a look on to emphasize this use case as it's very important for us to make the new API as clear and intuitive for our users as possible

Best,
Hubert

**Comment by psinger** [comment]
Indeed, there seem to be different behaviors between `source_files=[]` and `source_files=None`.

**Comment by HubertJaworski** [comment]
We have it documented [here](https://docs.neptune.ai/api-reference/neptune#init), but that's not very clear.

We use `None` - default value, to indicate `all files`, and explicitly passed empty table means `no files`

If you'd like, I can forward any feedback/suggestions directly to our design guys.
