### ISSUE TITLE
Neptune.ai with Horovod

### ISSUE THREAD

**Issue by tabmoo** [neptune-ai/neptune-client#509]
When using Neptune.ai with Horovod distributed training each GPU is assigned a run but metrics are assigned only to "aggregating" one with particular "rank". Standard technique in Horovod is like this:

`if hvd.rank() == 0:
    callbacks.append(ReduceLROnPlateau(factor=0.9, patience=3, verbose=1))
    ......
    ......
    callbacks.append(neptune_cbk)`

It works but can I exclude other ranks from being seen altogether by Neptune.ai?

**Comment by PiotrJander** [comment]
Hi @tabmoo 

Neptune does not integrate with Horovod just yet, but based on my limited knowledge of Horovod, achieving what you described should be possible by starting a Neptune experiment only after Horovod is initialized, conditioning on there being a particular Horovod rank.

In pseudocode:

```py
hvd.init()
if hvd.local_rank() == AGGREGATING_RANK():
   neptune.init(...)
```

and similarly wrapping all Neptune logging commands / callbacks in such conditionals.

Does this help?

**Comment by tabmoo** [comment]
Yes, it helped. Thanks!
