### ISSUE TITLE
MultiClass Classification Metrics

### ISSUE THREAD

**Issue by arkash20** [neptune-ai/neptune-client#511]
Hi,

I'm using nn for multi-class classification,
and I it would be great that a function will automatically create confusion matrix for multiclass,
a report like classification_report of sklearn.

Thanks,

Arkady

**Comment by kamil-kaczmarek** [comment]
Hi @arkash20,

Thanks for raising this suggestion. As of now, we do not provide functions for plotting confusion matrix or other diagnostics charts from data derived from model outputs.

However, one library that I recommend is Yellowbrick, that makes pretty plots for classification, regression, etc. ﻿Here is their docs for confusion matrix: https://www.scikit-yb.org/en/latest/api/classifier/confusion_matrix.html
﻿
﻿Hope this helps a bit.

Best,
Kamil
