### ISSUE TITLE
Error passing Neptune experiment between different processes

### ISSUE THREAD

**Issue by tdoublep** [neptune-ai/neptune-client#513]
I have a code base that uses Neptune for tracking experiments, and I tried to run it for the first time in a while and encountered failures related to passing the experiment object across processes.

Here is a minimal example:
```python
import neptune
from multiprocessing import Process

def func(experiment):
    print(experiment)

if __name__ == '__main__':

    project = neptune.init(project_qualified_name='project_anme')

    experiment = neptune.create_experiment(name='exp1', params = {})

    p = Process(target=func, args=(experiment, ))

    p.start()
    p.join()
```
which produces:
```bash
AttributeError: Can't pickle local object 'NeptuneAuthenticator.__init__.<locals>.session_factory'
```
I'm using Python 3.8.8 and neptune-client 0.9.5.

The same approach used to work fine with earlier versions of the neptune client.

**Comment by Herudaio** [comment]
Hi @tdoublep ! I've flagged this issue with our engineering team.

In the meantime if you are using neptune.new API you can do this in two ways:
1) Use `custom_run_id` in [`.init()`](https://docs.neptune.ai/api-reference/neptune#init) ([Read more on usage](https://docs.neptune.ai/how-to-guides/neptune-api/pipelines))
2) Create a run, pass just its ID to processes and re-connect to it from the multiple processes.

**Comment by aniezurawski** [comment]
Hi @tdoublep 

I can't say why exactly was it working earlier but this is not expected way to work with neptune.
Have in mind that Experiment object spawns few background threads (logging metrics asynchronously, pinging server etc).
Multiprocessing and multithreading does not cooperates well in general.

What do you want to achieve? If you want to work on the same experiment from multiple processes it is recommended to create Experiment object in every process individually.
In old API you can create experiment in first process and fetch it in others:
`exp = neptune.init().get_experiments(id="SAN-123")[0]`

However it is recommended to use new `neptune.new` API since it supports multiprocessing much better. See @Herudaio's comment above.

**Comment by tdoublep** [comment]
@aniezurawski @Herudaio thanks for the info. i deleted my project and created a new one so i could use neptune.new, and the approach using the `custom_run_id` does indeed seem to work. Here is the example adapted:

```python
import neptune.new as neptune
from multiprocessing import Process
from datetime import datetime

def func(custom_run_id):

    run = neptune.init(project='myproject/test', 
                       custom_run_id=custom_run_id)

    for i in range(0, 200):
        run['train/accuracy-p2'].log(0.99)

if __name__ == '__main__':
   
    dateTimeObj = datetime.now()

    custom_run_id = 'EXP-' + dateTimeObj.strftime("%d-%b-%Y-(%H:%M:%S)")

    run = neptune.init(project='myproject/test', 
                       custom_run_id=custom_run_id)

    for i in range(0, 100):
        run['train/accuracy-p1'].log(0.23)

    p = Process(target=func, args=(custom_run_id, ))

    p.start()
    p.join()
```
I guess the issue can be closed. Just have one observation: the string passed as `custom_run_id` does not seem to be related to the ID of the run in the UI, and doesn't even seem to be available in the UI at all, this behaviour was a little unexpected.

**Comment by tdoublep** [comment]
> 2. Create a run, pass just its ID to processes and re-connect to it from the multiple processes.

@Herudaio An additional question regarding (2): how can one query the ID of a run after creation in Python? This was not clear to me from the API documentation.

**Comment by Herudaio** [comment]
@tdoublep yes! It's located under `sys/id` path - https://docs.neptune.ai/api-reference/system-sys-namespace#runs-identifier-sys-id
