### ISSUE TITLE
The values of accuracy

### ISSUE THREAD

**Issue by Arseni1919** [neptune-ai/neptune-client#514]
I want not only to see the graph of accuracy, but also to see the list of values in neptune.new as it was in previous legacy version. Can you please correct it? Or can you describe me how to find the values? I did not find the way to do it except to explicitly log the values.
Thanks

**Comment by aniezurawski** [comment]
Hi @Arseni1919 

Some old features are still missing in new projects but they will be consistently added back. What can is say for sure is that in close future there will be possibility to download all values as a CSV files. I'm not sure about viewing them in the UI. @Herudaio can you say if this feature is going to come back?

**Comment by Arseni1919** [comment]
Why not? Personally to me, it will extremely convenient to see not only the graph but all the actual values somewhere in a small popup window nearby the graph. Please consider this feature.
Thanks!

**Comment by Herudaio** [comment]
@Arseni1919 Yes, we will be adding it back :) 
You should expect download as CSV next week, widget (to add to dashboard) to show a list of values probably the week after that, and both views available in All Metadata week or two after that :)

**Comment by Arseni1919** [comment]
Thank you!
