### ISSUE TITLE
Stop refresh

### ISSUE THREAD

**Issue by Arseni1919** [neptune-ai/neptune-client#515]
I scroll down some page (with graphs for example) and then the page automatically refresh itself and jumps up. Can you correct that please? Or can I stop the refreshing for a certain time?
Thanks

**Comment by jakubsy** [comment]
Hi @Arseni1919 

Thank you for your report.

In order for me to reproduce your issue I would need some more information:
1. What is the url on which this issue occured to you?
2. What browser are you using? What is its version?

Could you please contact us via in-app chat (the message bubble in the right bottom corner) or via email (contact@neptune.ai) and provide those details?

BR,
Jakub

**Comment by pkasprzyk** [comment]
No contact from user for more than 3 months. Closing, @Arseni1919 feel free to reopen or create a new issue if you're still having any problems.
