### ISSUE TITLE
Vertical split

### ISSUE THREAD

**Issue by Arseni1919** [neptune-ai/neptune-client#517]
Do you consider the option to add also a vertical split and not only horizontal?

Thanks

**Comment by Herudaio** [comment]
Hi @Arseni1919 !

We did, however, the rest of the UI is organized in a way that's more compatible with horizontal split than vertical one. We may add it at some point in the future, thanks for the suggestion! :)

**Comment by michalsustr** [comment]
Hi @@Arseni1919 , Michal from https://minfx.ai - you will be able to reorganize UI as you like. You can think of it as ML ops IDE. Please take a look at our project!
