### ISSUE TITLE
Broken log messages on terminal

### ISSUE THREAD

**Issue by dbdq** [neptune-ai/neptune-client#519]
Hello,

I just started using Neptune today and I'm already loving it. Thank you very much for developing this.

I'm using Keras + Tenforflow with Python (Anaconda) on Windows 10 and I'm having a lot of broken log messages on my Windows terminal when I use Neptune library. I have no problem monitoring chart and resources of my runs on my Neptune project page.

The problem is as follows with screenshot of the messages.
1. neptune.init() - [screenshot 1](https://drive.google.com/file/d/1I7zw4_VEdu3W79s2DxRYRwTaBuNrGtw4/view)
When I run this function using my API key and project name, it prints a lot of broken strings such as "Already visited %s". It seems as if it was trying to print some message without formatting argument.
2. neptune.create_experiment() - [screenshot 2](https://drive.google.com/file/d/1P8UHlkQ-CpApDISBlcuHjOnSNdEYwkvT/view)
Similar to above
3. while fitting a model - [screenshot 3](https://drive.google.com/file/d/1J8mJF5RT6lE2k4j_IamvrRoSA8Rnq4kt/view)
You can see that the broken strings causes the cursor to move down, breaking the Curses funcitonality and splitting the progress bar into multiple lines.

Although Neptune's dashboard is very nice, I still need to see some details on the terminal and this problem is making it very difficult to read my terminal messages.

May I know how I can solve this issue?

**Comment by HubertJaworski** [comment]
Hi,

I tracked down some of the wierd string you've been having

In particular, `Starting new HTTPS connection (%d): %s:%s` is done by Python's connectionpool via `log.debug` call

There are some methods of activating debug log level [described here](https://docs.python.org/3/howto/logging.html), maybe you've activated it

Can you share a snippet of your code so we can pinpoint the exact cause.

Best,
Hubert

**Comment by dbdq** [comment]
Hi, you were correct. I had some logging calls inside one of my imported packages. I think some of them must have set the default logging verbosity to DEBUG.

Now the problem is fixed. Thanks for your input!
