### ISSUE TITLE
Length of stream does not match given range

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#571]
Facts:
1. The following code fails with
```
Neptune server returned status 400.
{"code":400,"title":"Length of stream does not match given range","errorType":"BAD_REQUEST"}
```
2. if I set `n_jobs=1` it doesn't fail anymore
3. if I decrease the path length in HERE it doesn't fail anymore even with `n_jobs>1`

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from time import time, sleep

import neptune.new as neptune
import ray


@ray.remote
def f(x, run_id):
    run = neptune.init('XXX', run=run_id,
                       monitoring_namespace=f'monitoring/{x}')
    run[f'params/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/{x}/var'] = {'gags': 3}  # <------------- HERE
    sleep(2)


def main():
    n_jobs = 2
    run = neptune.init(
        'XXX',
        name='name',
        description='',
        source_files=[],
        flush_period=10,
        mode='async',
        monitoring_namespace='monitoring/main'
    )

    rid = run['sys/id'].fetch()
    run['params/main'] = {'asdf': 2}

    ray.init()
    ray.get([f.remote(i, rid) for i in range(n_jobs)])


if __name__ == '__main__':
    main()
```

**Comment by wjaskowski** [comment]
Actually I am not sure of 3. Maybe there is just a random factor instead.

**Comment by HubertJaworski** [comment]
HI @wjaskowski,

I was able to reproduce this using `ray-all==1.1.0` and `neptune-client==0.9.13`

I'm looking into what is the case - I'll goet back to you once we have more :)

Best,
Hubert

**Comment by HubertJaworski** [comment]
Looks like a bug on our end - every run within ray attempts to upload sources.

If this is blocking you can work around this by adding `source_files=[],` to run.init() withing `f`

I'm looking into solutions

**Comment by wjaskowski** [comment]
The workaround helps indeed. This is good enough for me. Thanks!

**Comment by HubertJaworski** [comment]
We tracked down what was happening, we created https://github.com/neptune-ai/neptune-client/pull/573 that should fix it.

Resumes tried to upload the sourcefiles again by default - we're changing this to make resume not upload any sources by default.

Once this fix is released we'll update docs to reflect this

**Comment by aniezurawski** [comment]
Should not occur anymore in 0.9.15.
