### ISSUE TITLE
BUG: Plot not visible through run['xyz'].upload(abc)

### ISSUE THREAD

**Issue by sakshiindolia** [neptune-ai/neptune-client#628]
### Describe the bug
I'm trying to save a plot using run['xyz'].upload(abc), however, the plot is not getting displayed.
### Reproduction
import matplotlib.pyplot as plt
plt.plot(hist.history["accuracy"])
plt.plot(hist.history['loss'])
plt.title("model accuracy")
plt.ylabel("Accuracy")
plt.xlabel("Epoch")
plt.legend(["Accuracy","loss"])
training_accuracy_loss_curve = plt.figure(figsize=(7, 7))
run['Parameters/Plots/acc_loss'].upload(training_accuracy_loss_curve)
### Expected behavior
The graph must be displayed with accuracy and loss curves but the graph is empty.
### Traceback
![image](https://user-images.githubusercontent.com/18024680/125920091-d48d9322-8f7a-48d6-b3e9-e73d5aa122c6.png)

**Comment by Raalsky** [comment]
Hey @sakshiindolia 

According to our docs here: https://docs.neptune.ai/api-reference/field-types#upload have you try to upload matplotlib plot explicitly as a figure object via `.gcf()` or upload as an Image https://docs.neptune.ai/api-reference/field-types#as_image ?
