### ISSUE TITLE
BUG: Multiple GPU creates duplicate experiments

### ISSUE THREAD

**Issue by stonelazy** [neptune-ai/neptune-client#655]
### Describe the bug
If we have more than one GPU's in the experiment, then for each of them a duplicate experiment run is being created in neptune

### Reproduction
Kindly run this as a python file.
https://colab.research.google.com/drive/10yscKBI0JEip1S3f6a_IrkC7GP56NcuT

### Expected behavior
Expected to see only one run in the runs table, but on running this it created 3 different runs in the Neptune.

**Comment by Blaizzy** [comment]
Hi @stonelazy 
I'm Prince Canuma a Data Scientist at Neptune.ai 

Try using the `custom_run_id` feature that allows you to log metadata from multiple files and processes to a **single run**.

Read more: https://docs.neptune.ai/api-reference/environment-variables#neptune_custom_run_id

Then let me know if this helps

Kind regards
