### ISSUE TITLE
BUG: Fetch_values does not work with numerical values in debug mode.

### ISSUE THREAD

**Issue by vivienrobert-wefox** [neptune-ai/neptune-client#663]
### Describe the bug
Calling fetch_values on a FloatSeries created in debug mode returns an empty dataframe.
### Reproduction
```import neptune.new as neptune
r = neptune.init(mode="debug")
r["t"].log(0)
r["t"].log(1)
r["t"].log(2)
print(r["t"].fetch_values())
```
### Expected behavior
The dataframe should contain the 3 entries
### Environment
Observed on neptune-client 0.10.3 to 0.10.5

### Extra Notes
I do not have the issue when not using debug mode.
fetch_last returns the expected value (2).
It works fine with "a", "b", "c" instead of 0, 1, 2.

**Comment by vivienrobert-wefox** [comment]
hello @kamil-kaczmarek 
I understand that but the docs read "In contrast to Offline mode, all data are stored only in memory." and it is not the case here as evidenced in my opening message. The values do not seem to be stored in memory for this particular case. I will add that it works as expected for non numerical values.

With numbers (doesn't work as expected):
```
>>> r = neptune.init(mode="debug")
Info (NVML): NVML Shared Library Not Found. GPU usage metrics may not be reported. For more information, see https://docs-legacy.neptune.ai/logging-and-managing-experiment-results/logging-experiment-data.html#hardware-consumption 
>>> r["t"].log(0)
>>> r["t"].log(1)
>>> r["t"].log(2)
>>> print(r["t"].fetch_values())
Empty DataFrame
Columns: []
Index: []
```

With text (works as expected).

```
>>> r = neptune.init(mode="debug")
>>> r["t"].log("a")
>>> r["t"].log("b")
>>> r["t"].log("c")
>>> print(r["t"].fetch_values())
   step value               timestamp
0     0     a 1970-01-01 01:00:42.342
1     1     b 1970-01-01 01:00:42.342
2     2     c 1970-01-01 01:00:42.342
```

**Comment by Blaizzy** [comment]
Hey @vivienrobert-wefox 
It is solved ✅
