### ISSUE TITLE
Feature Request: Downloading metrics from multiple runs is slow due to init.

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#683]
Usually, to make statistical analysis for experiments one needs to download metrics from multiple runs, like 50, 100 or even more. But downloading metrics or files from runs takes a lot of time since for each run, one need to execute `neptune.init`, which itself takes around 2 seconds. For 1000 runs it is 2000 seconds ~= 30 minutes. Would be nice if we could connect to the server only once but download things from multiple runs.

**Comment by aniezurawski** [comment]
Hi @wjaskowski 

Have you tried `fetch_runs_table()`? See https://docs.neptune.ai/api-reference/project
Let me know if it resolves this issue. We are aware that it still has poor filters so may be not enough in big projects for now but this method is meant for such usage.

**Comment by wjaskowski** [comment]
It doesn't solve the problem. By fetching metrics I meant fetching values
for each training epoch not only the last one.

**Comment by Herudaio** [comment]
@wjaskowski I understand the pain, but I'll be honest here - I don't think we will be changing anything in the near future :( For now, the main mode of working with Neptune is through the Run class. Changes here would be introducing another mode of communication that probably will be introduced, but more in a year or two than in next months.

What I can suggest for now is two things:
• We do have a "read-only" mode that should turn off most of the extra logging / capturing stdout & stderr so this should speed things up. In addition you can set to False all other "capture_{}"
• Cache the fetched results.

**Comment by wjaskowski** [comment]
I have been already using READ_ONLY. Doesn't READ_ONLY already imply that any logging (including the stdout and stderr) are turned off? I wonder what takes so much time during init...

**Comment by Herudaio** [comment]
> Doesn't READ_ONLY already imply that any logging (including the stdout and stderr) are turned off?
Yes, it does :) My bad, writing before the coffee :)

**Comment by aniezurawski** [comment]
Hi @wjaskowski 

I don't want to promise too much too early but there is a chance for some performance improvement for this case (multiple Runs) in some near future.

**Comment by wjaskowski** [comment]
Is that only my impression that today init/downloading is significantly faster or you have already made an improvement there?

**Comment by aniezurawski** [comment]
The promising tweaks will be client-side, not backend and it has not been released yet.

**Comment by wjaskowski** [comment]
Hmm, this would mean that there might be some sever/bandwitch issue as well
sometimes (unless I just subjectively misjudged the performance today or
earlier)

**Comment by aniezurawski** [comment]
Yes, we are aware of some issues server-side issues to be still fixed. But we are continuously working on improving performance of servers as well, so Neptune becomes better almost every day. :)

**Comment by aniezurawski** [comment]
@wjaskowski Please try new release 0.12.0. And let me know if there's any difference in performance. :)

**Comment by wjaskowski** [comment]
Thank you! There definitely is. It is hard to quantify it since it depends
on the use case.
