### ISSUE TITLE
BUG: in jupyter lab, I restart the kernel, activate neptune, and run all cells, but neptune cannot record my notebook

### ISSUE THREAD

**Issue by zwy-Giser** [neptune-ai/neptune-client#714]
### Describe the bug
 in jupyter lab, I restart the kernel, activate neptune, and run all cells, but neptune cannot record my notebook in notebook-checkpoint panel nor run-snapshot for notebook panel.

**Comment by Blaizzy** [comment]
Hi @zwy-Giser  thank you for reaching out 😃 

I'm Prince Canuma, Data Scientist at Neptune

Here is what's happening:

- When you restart the Jupyter kernel your notebook checkpoints may not be saved to Neptune nor connected to the Neptune Runs you created. 
- To fix that you need to re-activate your Notebook by clicking Activate in the Jupyter navigation. ✅ 

You can read more info in this section of our docs:
https://docs.neptune.ai/integrations-and-supported-tools/ide-and-notebooks/jupyter-lab-and-jupyter-notebook#configuration

**Comment by Blaizzy** [comment]
Let me know if this solves your problem!

**Comment by Blaizzy** [comment]
For now I'm closing this issue
