### ISSUE TITLE
Is there any convenient way to get a list of keys for a given node?

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#724]
I have the following situation:

output of `run.get_structure()`:
```python
(...)
'predictions': {'0': {'avg_r_diff': <neptune.new.attributes.atoms.file.File at 0x7fb9dd43d6a0>,
   'y': <neptune.new.attributes.atoms.file.File at 0x7fb9dd43d850>},
  '1': {'avg_r_diff': <neptune.new.attributes.atoms.file.File at 0x7fb9dd43d880>,
   'y': <neptune.new.attributes.atoms.file.File at 0x7fb9dd43d9d0>},
(...)
```

Indeed, ```run['predictions'].fetch()``` gives me:
```
{'0': {},
 '1': {},
(...)
```

But then when I call ```run['predictions/0']```, I get:
```
{}
```

How can I list all the keys (files) which are under 'predictions/0'?

**Comment by Blaizzy** [comment]
Hey @wjaskowski,

Happy new year! 🎊 



Does the answer provided by aniezurawski help you?

> ...Since `get_structure` return `dict` you can just call `enumerate` on it:
> 
> ```
> for idx, key in enumerate(r.get_structure()["predictions"]["0"]):
>     print(key)
> ```
> 
> or with `items()`:
> 
> ```
> for key, val in r.get_structure()["predictions"]["0"].items():
>     print(key)
> ```

**Comment by wjaskowski** [comment]
Yes. Thank you. This is the solution but I have the impression that the API in that place mirrors the internals of the database instead of being user-centered. That happens ;)
