### ISSUE TITLE
Feature Request: Log scikit-learn classification_report to neptune

### ISSUE THREAD

**Issue by talhaanwarch** [neptune-ai/neptune-client#726]
Is there a way to log scikit-learn classification_report to neptune?

**Comment by kamil-kaczmarek** [comment]
Hey @talhaanwarch,

You have two options for that:

1. Use [neptune-scikit-learn integration](https://docs.neptune.ai/integrations-and-supported-tools/model-training/sklearn) to automatically log classifier summary including classification report,
2. You can use neptune-client directly and simply log classification_report as image to your runs. It can be an [image](https://docs.neptune.ai/you-should-know/what-can-you-log-and-display#matplotlib-figure) or [interactive visulization](https://docs.neptune.ai/you-should-know/what-can-you-log-and-display#interactive-visualizations).

Hope this helps.

**Comment by kamil-kaczmarek** [comment]
Hey @talhaanwarch,

I'm thinking if the above info was helpful?

**Comment by talhaanwarch** [comment]
@kamil-kaczmarek how about converting classification_report to image? i think that is not included in neptune and not so easy and elegant to do. what about logging a dataframe, i think that would be more convenient

**Comment by Blaizzy** [comment]
Hey @talhaanwarch 

There are 3 ways to log your sklearn classification_report to neptune:

**1. Log it using the Neptune + Sklearn integration**

```
import neptune.new.integrations.sklearn as npt_utils

run = neptune.init(...)
run['visuals/classification_report'] = npt_utils.create_classification_report_chart(classifier, X_train, X_test, y_train, y_test)
```
**2. Log it as an image**

```
from yellowbrick.classifier import ClassificationReport
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
visualizer = ClassificationReport(classifier, support=True, is_fitted=True, ax=ax)
visualizer.fit(X_train, y_train)
visualizer.score(X_test, y_test)
visualizer.finalize()

# log to neptune as image
run = neptune.init(...)
run["visuals/classification_report_2"] = neptune.types.File.as_image(fig)
```

**3. Log it as pandas dataframe**

```
import pandas as pd
from sklearn.metrics import classification_report

df = pd.DataFrame.from_dict(classification_report(y_test, y_pred, target_names=class_names, output_dict=True))

# log to neptune as a pandas DF
run = neptune.init(...)
run["visuals/classification_report_3"] = neptune.types.File.as_html(df)
```

Here is a link to an example run of how all 3 would look like in the same order:

https://app.neptune.ai/common/sklearn-integration/e/SKLEAR-60757/all?path=visuals%2F

**Comment by Blaizzy** [comment]
@talhaanwarch let me know if this answers your question 😃

**Comment by Blaizzy** [comment]
Hey @talhaanwarch,

I'm closing this issue. 

Feel free to comment if you need any extra information.
