### ISSUE TITLE
Feature Request: delete an experiment?

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#727]
How can I delete a run/experiment from API?

**Comment by Blaizzy** [comment]
Hi @wjaskowski  

Prince Canuma here, Data Scientist at Neptune.ai

Currently, it's not available, but I will send your request to the engineering team!

Other than that, is there anything else I can help you with?

**Comment by lindseynield** [comment]
Hi, what is the priority status for this feature request? My team needs a way to programmatically delete runs using the python API.

**Comment by SiddhantSadangi** [comment]
Hello @lindseynield,
[neptune-client 0.16.8](https://github.com/neptune-ai/neptune-client/releases/tag/0.16.8) introduced the `trash_objects()` method that you can use to delete Neptune runs, models, and model versions.
You can read more about it in our docs: https://docs.neptune.ai/api/management/#trash_objects

I am closing this feature request for now, but please feel free to reach out in case you have any other questions.
