### ISSUE TITLE
Feature Request: fetch runs table with selected fields only

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#730]
In my project I have 800 runs each of which has 18000 hyperparameters. In result, 
```python
project.fetch_runs_table()
``` 
takes 51 seconds.

I rarely need all those parameters. Usually, I need just `run_ids` or a few selected columns. Maybe you also do not need additional traffic ;). I wish I had sth like:

```python
project.fetch_runs_table(columns=['sys/run_id', 'node/param1'])
```

**Comment by wjaskowski** [comment]
Today it takes 1 min 46 seconds for `fetch_runs_table`. It is getting completely unusable...

**Comment by wjaskowski** [comment]
My dataframe obtained by `fetch_runs_table()` takes 1.4GB. Are you planning to do anything about this issue? 

![image](https://user-images.githubusercontent.com/4952605/184149911-7b23fc0a-2552-459e-8864-06f577decf64.png)

**Comment by wjaskowski** [comment]
At the same time the object from which the pandas dataframe is converted from takes >7GB:
![image](https://user-images.githubusercontent.com/4952605/184152510-6eb8fdf6-bfd2-42b5-b4c2-6e2effd028cd.png)

Simply unusable.

**Comment by Herudaio** [comment]
Hey @wjaskowski, filtering the results by column names should be available soon. Optimistically within 2 weeks, but may be up to 4 - it's already in the short dev queue.
