### ISSUE TITLE
Feature Request: flag to disable neptune during tests

### ISSUE THREAD

**Issue by bartoszptak** [neptune-ai/neptune-client#742]
### Is your feature request related to a problem? Please describe.
I want to be able to use a flag to test the code without sending runs to the server. When the flag is active, neptune.ai is in the code but does not log information to the server.

### Describe the solution you'd like
e.g. : 
`NEPTUNE_API_TOKEN="test" python my_script.py`
or:
`NEPTUNE_TEST_MODE="1" python my_script.py`

**Comment by Raalsky** [comment]
Hey @bartoszptak,

Have you already checked our docs especially the Connection Modes? https://docs.neptune.ai/you-should-know/connection-modes. The `debug` should be well suited for your case.

In the context of feature request it should be translated to made `neptune.init(..., mode="<>")` being able to override via environment variable like `NEPTUNE_MODE`.
