### ISSUE TITLE
BUG: 'neptune' is not a package

### ISSUE THREAD

**Issue by Basti110** [neptune-ai/neptune-client#749]
### Describe the bug
Hey, 
i tried to use the hello world example of Neptune with my project path and Token ID. But I'm not able to use Neptune on my system (Ubuntu 20, Python 3.8.1). There is an error that  neptune is not a package. 

`ModuleNotFoundError: No module named 'neptune.new'; 'neptune' is not a package` 
Also a docker Version (Ubuntu 20, Python 3.8.5) ist not working.  

I reinstalled `neptune-client` multiple times with pip and tried it also with a docker enviroment (Ubuntu 20, Python 3.8.5). But the result was still the same. 
### Reproduction
```
import neptune.new as neptune
run = neptune.init(
    project="<PROJECT>",
    api_token="<TOKEN>",
)  # your credentials

params = {"learning_rate": 0.001, "optimizer": "Adam"}
run["parameters"] = params

for epoch in range(10):
    run["train/loss"].log(0.9 ** epoch)

run["eval/f1_score"] = 0.66

run.stop()
```
ERROR: 
`ModuleNotFoundError: No module named 'neptune.new'; 'neptune' is not a package` 

When I try another example of this git readme with:
```
import neptune

neptune.init('my_workspace/my_project')
```
then I get 
`AttributeError: partially initialized module 'neptune' has no attribute 'init' (most likely due to a circular import)`

**Comment by Basti110** [comment]
Okay suddenly it is working in both enviroments.

**Comment by kamil-kaczmarek** [comment]
Hey @Basti110 ,

Happy to see that the problem disappeared.

Let us know if you will have other problems :)
