### ISSUE TITLE
BUG: sys/status is 'idle' but 'Inactive' in UI

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#763]
### Describe the bug
When I execute `fetch_runs_table` the `sys/status` column contains `idle` but it should be `Inactive` according to the web UI and documentation.

**Comment by Blaizzy** [comment]
Hey @wjaskowski 

Prince here, from Neptune.ai

We are still using **idle** and **running** which are legacy states/statuses in the backend, we don't support the new states you see in the UI yet. But we are working on it.

For now, please use the **idle** and **running** states.


You can translate them in the following way:
* Idle -> inactive 
* running -> active

Example:
`# Fetch only inactive runs`
`runs_table_df = project.fetch_runs_table(state='idle').to_pandas()`

Thanks for flagging this, we will update the docs as soon as possible to avoid this confusion.

**Comment by Blaizzy** [comment]
Let me know if this solves your issue!
