### ISSUE TITLE
about check train dataset method

### ISSUE THREAD

**Issue by NeekHua** [neptune-ai/neptune-client#802]
Great job.
And I want check my train image ,I should add which code.
Looking forward to your reply

**Comment by Blaizzy** [comment]
Hi @NeekHua,

Prince Canuma here, a Data Scientist at Neptune.ai

Glad to help you with this one,

What do you mean by checking train images? Can you elaborate?

Do you mean visualizing your training images in the Neptune? If so, you can do that by using `.upload()` method for single images or `.log()` method for series of images.

- **Single image**
```
from neptune.new.types import File
run = neptune.init(...)

run['train/bounding_boxes'].upload('bboxes.png')
```


- **For series/batch of images**
```
from neptune.new.types import File
run = neptune.init(...)

for i in range(valid_nr):
    ith_path = ...
    run['valid/misclassified'].log(File(ith_path))
```

Docs: https://docs.neptune.ai/you-should-know/what-can-you-log-and-display#images

Then you can visualize it in the Neptune UI by following the link you get from running your script. Example link: https://app.neptune.ai/common/colab-test-run/e/COL-225

**Comment by NeekHua** [comment]
@Blaizzy 
I see. Thank you very much for your reply

**Comment by Blaizzy** [comment]
Most welcome!

If you have any other questions please don't hesitate to reach out 👍
