### ISSUE TITLE
Feature Request: Add support for OpenCV images

### ISSUE THREAD

**Issue by SiddhantSadangi** [neptune-ai/neptune-client#831]
Currently, images read using cv2.imread() don't render correctly when uploaded directly to Neptune.

To render them correctly, they have to be:

1. converted to RGB format
```
img_bgr = cv2.imread("OpenCV_logo.png", cv2.IMREAD_UNCHANGED)
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
```
2. scaled
```
run["img_rgb_scaled"].upload(neptune.types.File.as_image(img_rgb/255))
```

These steps should be added to the client side itself while uploading such images.

Sample run with both scaled/unscaled rgb/bgr images: https://app.neptune.ai/common/quickstarts/e/QUI-75486/all?path=&attribute=img_rgb_scaled

**Comment by Blaizzy** [comment]
Hey Siddhant,

I have submitted the feature request to the engineering team,

Will keep you updated.
