### ISSUE TITLE
Feature Request: Add support for Seaborn figures

### ISSUE THREAD

**Issue by SiddhantSadangi** [neptune-ai/neptune-client#832]
The client currently does not support seaborn figures out-of-the-box, and they need to be converted to matplotlib format for upload

```
# Generate chart
seaborn_fig = ...

# Convert Seaborn object to Matplotlib format (matplotlib.figure.Figure)
figure = seaborn_fig.fig

# Log figure to run
run["seaborn-img"].upload(neptune.types.File.as_image(figure))
```

This step should be handled within the client

**Comment by Blaizzy** [comment]
Hey Siddhant,

Thanks for submitting this feature request. I have passed it to the engineering team. 

I will keep you informed if there is any news.
