### ISSUE TITLE
BUG: Can not init new neptune run

### ISSUE THREAD

**Issue by bchalk101** [neptune-ai/neptune-client#862]
### Describe the bug
Init a neptune run is raising an Exception `AttributeError: type object 'Experiment' has no attribute 'type'`. 

The code was working fine till today, with the new version of neptune client.
### Reproduction
Running this line raised the exception:
`self._run = neptune.init(project=self.project_name, api_token=self.neptune_token, mode=self.mode, tags=[self.training_id])`

### Traceback
```
  File "/clients/neptune_client.py", line 24, in run
    self._run = neptune.init(project=self.project_name, api_token=self.neptune_token, mode=self.mode, tags=[self.training_id])
  File "lib/python3.7/site-packages/neptune/new/internal/init/run.py", line 266, in init_run
    checkpoint_id=checkpoint_id,
  File "/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 361, in create_run
    additional_params=additional_params,
  File "lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 413, in _create_experiment
    return ApiExperiment.from_experiment(experiment)
  File "lib/python3.7/site-packages/neptune/new/internal/backends/api_model.py", line 54, in from_experiment
    type=ContainerType.from_api(response_exp.type),
  File "lib/python3.7/site-packages/bravado_core/model.py", line 421, in __getattr__
    type(self).__name__, attr_name,
```
### Environment
__This is a reduced version of the env__

neptune-client            0.15.1             pyhd8ed1ab_0    defaults
neptune-tensorflow-keras  0.9.9              pyhd8ed1ab_1    defaults
bravado                   11.0.3             pyhd8ed1ab_0    defaults
bravado-core              5.17.0             pyh9f0ad1d_0    defaults

**The operating system you're using:**
**The output of `python --version`:** Python 3.7.12

**Comment by kamil-kaczmarek** [comment]
Hey @bchalk101 ,

Sorry for the late reply :pray: 

- are you on Win or Linux?

Please upgrade to the latest version `0.15.2` -> let me know if the problem continues?

**Comment by AlexandrZotovSBD** [comment]
Hi, @kamil-kaczmarek 
Got the same problem. neptune-client version `0.15.2`

**Comment by kamil-kaczmarek** [comment]
hey @AlexandrZotovSBD ,

Thanks for reporting. Let me ask few questions:

* Are you on Win or Linux?
* Do you work with some Neptune integration?
* Can you paste code snippet that reproduce the error, or piece of code that causes this?

**Comment by AlexandrZotovSBD** [comment]
Thanks for quick response, @kamil-kaczmarek!
I'm on linux, python 3.7.12 (also tried with 3.9 with same result)
I've connected jupyterlab to neptune.
`run = neptune.init(project=NEPTUNE_PROJECT, 
                   api_token=NEPTUNE_API_TOKEN,
                  )`
Actually I have managed this issue  with downgrading neptune-client to 0.12.1. Not a perfect solution but it works.

**Comment by pkasprzyk** [comment]
@AlexandrZotovSBD @bchalk101 could you confirm: are you using Neptune SaaS, or a on-premise deployment?

**Comment by AlexandrZotovSBD** [comment]
@pkasprzyk on-premise deployment

**Comment by pkasprzyk** [comment]
Unfortunately it seems the 0.15.X versions ("model registry") are not supported on your deployment. For now `0.14.3` should be working correctly for you, but please reach out to the sales rep handling your contract to discuss the situation.

**Comment by AlexandrZotovSBD** [comment]
Thanks. It seems to be wise to add some kind of check of compatibility of server and client versions.
