### ISSUE TITLE
project_qualified_name is too long and unintuitive

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/neptune-client#87]
It is a bit frustrating to type `project_qualified_name` every time I run `neptune.init()`

Could that be changed to `project_name` ?

Also, is there any other way to pass the `project_name`, like CLI?

**Comment by kamil-kaczmarek** [comment]
Hey,

100% agree, that we need to change `project_qualified_name`.
Now passing this name in possible in `init` and `get_project` functions.

**Comment by aniezurawski** [comment]
@jakubczakon It is possible to pass project name via `NEPTUNE_PROJECT` environment variable.

**Comment by jakubczakon** [comment]
@aniezurawski awesome thanks!

**Comment by Herudaio** [comment]
@jakubczakon with the recent update to our API we change to simply `project`. You can also pass it still as `NEPTUNE_PROJECT` environment variable.
