### ISSUE TITLE
BUG: Can't log to organisation workspace using neptune-client v0.15.2+ (on-prem)

### ISSUE THREAD

**Issue by cah-parita-desai** [neptune-ai/neptune-client#881]
Hi Team,

We are using Neptune AI - SaaS version in our organization.

While trying to use Neptune-Client 0.15.2 version as below, it gives error while trying to create run.
import neptune.new as neptune
import os

os.environ['NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE']='TRUE'

run = neptune.init(project="", api_token="")
Given values in both project & api_token

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/bravado_core/model.py in __getattr__(self, attr_name)
    416         try:
--> 417             return self[attr_name]
    418         except KeyError:

/opt/conda/lib/python3.7/site-packages/bravado_core/model.py in __getitem__(self, property_name)
    446         """
--> 447         return self.__dict[property_name]
    448 

KeyError: 'type'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_4816/3016530260.py in <module>
----> 1 run = neptune.init(project="cardinal-health/test", api_token="...==")

/opt/conda/lib/python3.7/site-packages/neptune/new/internal/init/run.py in init_run(project, api_token, run, custom_run_id, mode, name, description, tags, source_files, capture_stdout, capture_stderr, capture_hardware_metrics, fail_on_exception, monitoring_namespace, flush_period, proxies, capture_traceback, **kwargs)
    264             custom_run_id=custom_run_id,
    265             notebook_id=notebook_id,
--> 266             checkpoint_id=checkpoint_id,
    267         )
    268 

/opt/conda/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py in wrapper(*args, **kwargs)
    100 
    101             try:
--> 102                 return func(*args, **kwargs)
    103             except requests.exceptions.InvalidHeader as e:
    104                 if "X-Neptune-Api-Token" in e.args[0]:

/opt/conda/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py in create_run(self, project_id, git_ref, custom_run_id, notebook_id, checkpoint_id)
    359             parent_id=project_id,
    360             container_type=ContainerType.RUN,
--> 361             additional_params=additional_params,
    362         )
    363 

/opt/conda/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py in _create_experiment(self, project_id, parent_id, container_type, additional_params)
    411                 self.leaderboard_client.api.createExperiment(**kwargs).response().result
    412             )
--> 413             return ApiExperiment.from_experiment(experiment)
    414         except HTTPNotFound:
    415             raise ProjectNotFound(project_id=project_id)

/opt/conda/lib/python3.7/site-packages/neptune/new/internal/backends/api_model.py in from_experiment(cls, response_exp)
     52         return cls(
     53             id=response_exp.id,
---> 54             type=ContainerType.from_api(response_exp.type),
     55             sys_id=response_exp.shortId,
     56             workspace=response_exp.organizationName,

/opt/conda/lib/python3.7/site-packages/bravado_core/model.py in __getattr__(self, attr_name)
    419             raise AttributeError(
    420                 'type object {0!r} has no attribute {1!r}'.format(
--> 421                     type(self).__name__, attr_name,
    422                 ),
    423             )

AttributeError: type object 'Experiment' has no attribute 'type'

**Comment by Blaizzy** [comment]
Hi 

Prince Canuma here, a Data Scientist at Neptune.ai 

Can you run the following script:

`import neptune.new as neptune 
run = neptune.init(project="common/showroom", api_token="ANONYMOUS")
run["test"]=123`

Let me know if it ends without any errors for you

**Comment by cah-parita-desai** [comment]
Hi Prince Canuma,

I was able to run it without any errors.

But i still see the same error while connecting to my organization's neptune from jupyter notebook for which i have raised the issue.

Thanks
Parita.

**Comment by Blaizzy** [comment]
Great! 

Then it must be something else. 

Quick question, does the project "test" exist under the workspace "cardinal-health"?

**Comment by cah-parita-desai** [comment]
Hi,

Yes. "test" project does exist under cardinal-health workspace.
We are facing the same issue with other projects too.

Just for information, incase this helps to you understand/troubleshoot better, 

not getting any error on using "init_project" & parameters are getting logged under project-metadata.

Thanks!

**Comment by Blaizzy** [comment]
Can you send me a minimal reproducible code that generates this error so I can run it and dig deeper

**Comment by cah-parita-desai** [comment]
import neptune.new as neptune
import os
os.environ['NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE']='TRUE'

run = neptune.init(project="cardinal-health/test", api_token="") 
Can't share my api token here.

But this is the piece of code am using to connect to NeptuneAI using neptune-client (0.15.2)

Thanks

**Comment by cah-parita-desai** [comment]
Also, even if i get below error
"AttributeError: type object 'Experiment' has no attribute 'type'"

Run get created but when i try to log any parameters like below

import neptune.new as neptune
import os
os.environ['NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE']='TRUE'

run1 = neptune.init(project="cardinal-health/test", api_token="")
run1["test"]=123

I get below error:-

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_3259/138164699.py in <module>
----> 1 run1["test"]=123

NameError: name 'run1' is not defined

Thanks!

**Comment by Blaizzy** [comment]
Let me see if I understand it.

The code you sent works with project "common/showroom" and token "ANONYMOUS" but it doesn't work with your own, right?

**Comment by Blaizzy** [comment]
`NameError Traceback (most recent call last)
/tmp/ipykernel_3259/138164699.py in 
----> 1 run1["test"]=123

NameError: name 'run1' is not defined

Thanks! `

This is a Python error I think you didn't run the neptune.init() code cell

**Comment by cah-parita-desai** [comment]
> Let me see if I understand it.
> 
> The code you sent works with project "common/showroom" and token "ANONYMOUS" but it doesn't work with your own, right?

That's right

**Comment by cah-parita-desai** [comment]
> ```
> /tmp/ipykernel_3259/138164699.py in 
> ----> 1 run1["test"]=123
> 
> NameError: name 'run1' is not defined
> ```
> 
> This is a Python error I think you didn't run the neptune.init() code cell

I did ran neptune.init() cell.

**Comment by Blaizzy** [comment]
Then you forget assign neptune.init() to run1 variable.

**Comment by Blaizzy** [comment]
Please check the variable name you are assigning neptune.init() to because it has to be the same one you will use to log metadata

**Comment by cah-parita-desai** [comment]
I have done it correctly.

Kindly refer to the screenshot attached.
![Neptune](https://user-images.githubusercontent.com/66297999/163408779-7c73a2d6-d834-4033-a3d0-f79cfa73094e.PNG)


Thanks!

**Comment by Blaizzy** [comment]
What is the output when you run that cell?

**Comment by cah-parita-desai** [comment]
Hi
I saw your message this morning. 
Kindly let me know if we can connect sometime today.
Thanks!

**Comment by Blaizzy** [comment]
Hi,

Thank you for your patience

Yesterday I was Out Of Office,

But I'm back and we can connect today via intercom as I suggested!

**Comment by cah-parita-desai** [comment]
Hi,

But i don't see "Intercom" icon in neptune UI.

Kindly advise

Thank you!

**Comment by Blaizzy** [comment]
Thank you for reporting this issue!

As we discussed during our call, I have informed the devs about it and will get back to you as soon as they give me an update

**Comment by Blaizzy** [comment]
For now, you can continue to log your experiments with the neptune-client v0.15.1!

**Comment by cah-parita-desai** [comment]
Would like to understand as what is the update on the issue??

Why this has been closed?

**Comment by Blaizzy** [comment]
Hi @cah-parita-desai,

Rest assured we are working on it! 👍 

The issue was closed because we are already in touch on Intercom, and all updates will be communicated there!

Is that ok?

**Comment by cah-parita-desai** [comment]
Hi

Thank you for quick update.

I would rather suggest to keep this issue open until it's resolved.

With this if anyone else is facing similar issue, would get to know & won't create another issue for the same bug.

Regards,
Parita.

**Comment by Blaizzy** [comment]
That's a good suggestion!

I will keep it open until it's fixed.

**Comment by Blaizzy** [comment]
Hi @cah-parita-desai 

A new version on-prem has been released and it addresses this issue,

Please send a mail to kamil.kaczmarek@neptune.ai for more info.
