### ISSUE TITLE
Feature Request: Configure info output to stdout

### ISSUE THREAD

**Issue by fzimmermann89** [neptune-ai/neptune-client#892]
### Issue
Neptune writes some information to stdout. This can break for example the pytorch lightning progress bar.
Example: The run URL is written in https://github.com/neptune-ai/neptune-client/blob/bd66c94db7b285715132787582b3da6108f02605/neptune/new/metadata_containers/metadata_container.py#L350 

### Describe the solution you'd like
A `silent` keyword to neptune.init() to silence all click.echo outputs

### Additional context
Sometimes it might be easier to explicitly get the information from Neptune and output it manually than have neptune output directly.

**Comment by kamil-kaczmarek** [comment]
hey @fzimmermann89 

Thanks a lot for the comment. I'm passing it to the product team for further consideration.

I did not encounter issues when few libs write to the stdout (like Lightning + Neptune). Can you perhaps show what went wrong in your case? Maybe I'l be able to suggest something.

**Comment by fzimmermann89** [comment]
Thanks for the offer. My issues were caused by creating the Neptune run manually after the progress bar has already been created (to reuse code between different projects). 
So the URL was printed in the same line as part of the progress bar, followed by a new line and a new progress bar. 
This makes the logs a bit more chaotic to grep through down the line.. I spent some time working around this by monkey patching, but it would be nice to just have to option to completely silent neptune.

**Comment by kamil-kaczmarek** [comment]
Thanks!

Seems that you are printing some metadata (not only progbar) to the stdout, correct? In such case I'm curious if you considered logging it to Neptune instead, for all visualizing / analyzing features?

We also sent some info to stderr, which is occasionally important if sth. goes wrong.

**Comment by kamil-kaczmarek** [comment]
@Blaizzy forwarding this discussion to you :)

**Comment by Blaizzy** [comment]
Hi @fzimmermann89 

Prince here, a Data Scientist at neptune.ai,

> So the URL was printed in the same line as part of the progress bar, followed by a new line and a new progress bar.
This makes the logs a bit more chaotic to grep through down the line.. I spent some time working around this by monkey patching...

I would love to see your logs without and without the monkey patching, perhaps this will help us make a better suggestion.

If you don't mind you can send them to my email: prince.canuma@neptune.ai

**Comment by Blaizzy** [comment]
Hey @fzimmermann89 

I'm just checking in to see if you still need help with this issue

**Comment by fzimmermann89** [comment]
Hi,

thanks for following up. I don't really need help, but would still prefer to be able to simply silent neptune during training.

So this is more a feature request than a request for help and I would understand if you choose to not implement this any time soon.


best
Felix

**Comment by Blaizzy** [comment]
We appreciate user feedback it helps us improve the product. 

You said you spent some time working on a monkey patch, do you mind sharing it with me as well as the logs you get before and after?

This will help us pass complete feedback to the product team and they will make the final decision on whether it's something they want to implement now or later.

**Comment by Blaizzy** [comment]
Hey there, just checking to see if you still need help with this or if you have any other questions or doubts.

**Comment by Blaizzy** [comment]
Stale issue
