### ISSUE TITLE
x and y seem to be switched in send_metric

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/neptune-client#93]
It seems that when I send metrics through the `send_metric` method, it gets sent to x not y dimension.
It is later visualized as if it was y.

**Comment by aniezurawski** [comment]
@jakubczakon how exactly does your `send_metric` call look like?

**Comment by jakubczakon** [comment]
Well I guess the problem is that if you look at equivalent options:

option 1
```python
with neptune.create_experiment():
    neptune.send_metric('accuracy', 0.9)
```
option 2
```python
with neptune.create_experiment():
    neptune.send_metric(channel_name='accuracy', x=0.9)
```
option 3
```python
with neptune.create_experiment():
    neptune.send_metric(channel_name='accuracy', x=1, y=0.9)
```

What was x in option 2 becomes y in option 3. 
What I expected to be an option was this:

option 4 (doesn't work)
```python
with neptune.create_experiment():
    neptune.send_metric(channel_name='accuracy', y=0.9)
```

**Comment by hotzenklotz** [comment]
Same for me. x and y are swapped.

**Comment by aniezurawski** [comment]
@jakubczakon @hotzenklotz 
If you want `x` to be auto incremented (option 4 and 2 as well) just use

```neptune.send_metric(channel_name='accuracy', 0.9)```

So without named parameter. I agree it can be misleading if you use named parameter with only one value provided.
There are three recommended ways to call this method:

```neptune.send_metric(channel_name='accuracy', 0.9)```
```neptune.send_metric(channel_name='accuracy', 1, 0.9)```
```neptune.send_metric(channel_name='accuracy', x=1, y=0.9)```

It is still possible to call:

```neptune.send_metric(channel_name='accuracy', x=0.9)```

which is equal to:

```neptune.send_metric(channel_name='accuracy', 0.9)```

But it is not recommend. We will consider rearranging this method, so such misleading call won't be possible.
