### ISSUE TITLE
BUG: Hello World example does not work

### ISSUE THREAD

**Issue by ofurman** [neptune-ai/neptune-client#951]
### Describe the bug
Hello world example does not work. The same issue I have when integrating neptune into my code
### Reproduction
```
import neptune.new as neptune
run = neptune.init(
    project="my_workspace/my_project",
    api_token="my_api_token", 
)  # your credentials
params = {"learning_rate": 0.001, "optimizer": "Adam"}
run["parameters"] = params
for epoch in range(10):
    run["train/loss"].log(0.9 ** epoch)
run["eval/f1_score"] = 0.66
run.stop()
```
### Expected behavior
Code runs and data is logged to neptune.ai
### Traceback
Traceback (most recent call last):
  File "test_neptune.py", line 3, in <module>
    run = neptune.init(
  File "/home/oleksii/work/test/env/lib/python3.8/site-packages/neptune/new/internal/init/run.py", line 256, in init_run
    api_run = backend.create_run(
  File "/home/oleksii/work/test/env/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/home/oleksii/work/test/env/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 342, in create_run
    return self._create_experiment(
  File "/home/oleksii/work/test/env/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 396, in _create_experiment
    return ApiExperiment.from_experiment(experiment)
  File "/home/oleksii/work/test/env/lib/python3.8/site-packages/neptune/new/internal/backends/api_model.py", line 54, in from_experiment
    type=ContainerType.from_api(response_exp.type),
  File "/home/oleksii/work/test/env/lib/python3.8/site-packages/bravado_core/model.py", line 419, in __getattr__
    raise AttributeError(
AttributeError: type object 'Experiment' has no attribute 'type'

### Environment
**The output of `pip list`:**
```
Package                Version  
---------------------- ---------
attrs                  21.4.0   
boto3                  1.24.36  
botocore               1.27.36  
bravado                11.0.3   
bravado-core           5.17.0   
certifi                2022.6.15
charset-normalizer     2.1.0    
click                  8.1.3    
future                 0.18.2   
gitdb                  4.0.9    
GitPython              3.1.27   
idna                   3.3      
jmespath               1.0.1    
jsonref                0.2      
jsonschema             3.2.0    
monotonic              1.6      
msgpack                1.0.4    
neptune-client         0.16.4   
numpy                  1.23.1   
oauthlib               3.2.0    
packaging              21.3     
pandas                 1.4.3    
Pillow                 9.2.0    
pip                    20.0.2   
pkg-resources          0.0.0    
psutil                 5.9.1    
PyJWT                  2.4.0    
pyparsing              3.0.9    
pyrsistent             0.18.1   
python-dateutil        2.8.2    
pytz                   2022.1   
PyYAML                 6.0      
requests               2.28.1   
requests-oauthlib      1.3.1    
s3transfer             0.6.0    
setuptools             44.0.0   
simplejson             3.17.6   
six                    1.16.0   
smmap                  5.0.0    
swagger-spec-validator 2.7.4    
typing-extensions      4.3.0    
urllib3                1.26.11  
websocket-client       1.3.3
```
**The operating system you're using:**
**Python 3.8.10**

**Comment by SiddhantSadangi** [comment]
Hello @ofurman !

We are not able to reproduce this issue. Tried on both Windows and Linux using Python 3.8.10 and your package versions.

Are you running this in a virtual environment? Can you try running the code you've provided in a new virtual environment?

If you still face issues, we can jump on a call to troubleshoot.

**Comment by SiddhantSadangi** [comment]
Hello @ofurman , just checking if you were able to resolve this issue.

**Comment by Blaizzy** [comment]
Hey @ofurman 

I’m closing this issue as it’s stale,

Feel free to leave a comment here if the issue persists so we can help you solve it,

Until then have a great day.
