### ISSUE TITLE
Model Checkpoint Logging Issue

### ISSUE THREAD

**Issue by ndahiya3** [neptune-ai/neptune-client#989]
I am having an issue with logging model checkpoint with pytorch lightning. If I create a model checkpoint  like so:
`
latest_checkpoint = ModelCheckpoint(dirpath=exp_dir, save_last=True)
`
then the latest and last model.ckpt get's saved in the experiment runs. However, if I create a model checkpoint like so:
`
best_eval_checkpoint = ModelCheckpoint(dirpath=exp_dir, monitor='avg_val_loss', filename='best-eval-{epoch}-{step}-{avg_eval_loss:.2f}')
`
then this doesn't get logged. I suspect it may be because of the filename pattern but I am not sure.
Any help regarding this is appreciated as the best evaluation model checkpoint is the most important to save to be actually used for inference.

**Comment by Blaizzy** [comment]
Hey @ndahiya3 

Thanks for reaching out, 

I'm trying to replicate your issue and assess if it's a bug or not.

I will come back to you with my findings as soon as possible.

**Comment by Blaizzy** [comment]
I have managed to replicate your issue. 

I think it's related to PyTorch Lightning itself.

Would you mind running the same code without neptune and let me know if your checkpoints get saved in the local machine.

**Comment by ndahiya3** [comment]
Thanks for looking into this issue. All the desired checkpoints are being saved locally, in both cases, with and without neptune.

**Comment by Blaizzy** [comment]
Interesting, in my case, when I pass the filename it doesn't create any checkpoints.

I will double-check this and possibly reach out to the PTL team.

Because Neptune is logging checkpoints without issues with the default ModelCheckpoint config.

**Comment by Blaizzy** [comment]
Closing this issue as it's stale.

**Comment by Blaizzy** [comment]
Re-opening

Upon closer inspection, I noticed that this bug arises when running scripts in GPU environments.
